### ISSUE TITLE
Photo app gets stuck in  general view at around 150 photos

### ISSUE THREAD

**Issue by nemihome** [nextcloud/photos#147] opened 2020-01-21 16:52 UTC
**Decription**
If I scroll down the app gets stuck after around 150 photos. After that I see some placeholders and it is not possible to scroll down further.

![image](https://user-images.githubusercontent.com/60146462/72824657-edff6780-3c75-11ea-8cbc-3d5bb6f1bb34.png)

If I scroll app afterwards I will get a dead screen:
![image](https://user-images.githubusercontent.com/60146462/72824735-0f605380-3c76-11ea-895a-854565d959ce.png)

If I reload the page or switch to files and back to photos it is working again but only until I reach the same photos.

If I open the photos in the subfolders this is working even if there are 500 in a subfolder. In total I have around 3000 Photos which is not so much in my opinion.

**Logs**
I only see a lot of infomassages but no errors

Info | no app in context | Deprecated event type for OCP\IPreview:PreviewRequested: Symfony\Component\EventDispatcher\GenericEvent
-- | -- | --

![image](https://user-images.githubusercontent.com/60146462/72835450-09c13880-3c8b-11ea-9bba-6bcc4e02f4f9.png)

**Environment**
Nextcloud 18
PHP FPM 7.41

**Comment by skjnldsv** [comment] 2020-01-22 09:41
Hi :)
Could you expend the last javascript error?

**Comment by nemihome** [comment] 2020-01-22 15:13
Hi, sure, but there is not much info ;)

![image](https://user-images.githubusercontent.com/60146462/72906218-25334e80-3d32-11ea-955d-bd90095cdeb1.png)

**Comment by skjnldsv** [comment] 2020-01-22 15:39
What browser?

**Comment by nemihome** [comment] 2020-01-22 15:54
Google Chrome 79.0.3945.130 

That are the last errors in Firefox. The security policy error is a bit confusing. This is not showing up in Google Chrome and there is no detail information what is missing. But on the other hand this is handled by nextcloud itself as far as I know.
![image](https://user-images.githubusercontent.com/60146462/72909572-8873af80-3d37-11ea-9eb0-f29da2b3f152.png)


![image](https://user-images.githubusercontent.com/60146462/72909168-db993280-3d36-11ea-9710-fc455a7a59fe.png)

**Comment by skjnldsv** [comment] 2020-01-22 15:57
That is super weird.
You're using latest stable 18, right? Not beta nor rc?

**Comment by nemihome** [comment] 2020-01-22 16:08
Yeah, latest stable.  The thing is if I don't use the "main view" (hitting the app symbol and scrolling down) and  and open the folders one by one this does not happen (and in some folders are around 600 pictures). Some pictures are in more than one folder. Which means there are some duplicates.  But it allways happen at around 150 photo pictures. Sometimes one or two more or less are shown before it crashes.

**Comment by skjnldsv** [comment] 2020-03-20 19:05
Hey! :)
Have you tried 18.0.2 yet?

**Comment by nemihome** [comment] 2020-03-20 19:30
Yeah, still the same problem. No change.

**Comment by skjnldsv** [comment] 2020-03-20 19:49
Still seeing the last errors though?
Regarding the fact that is get stuck, it's probably a duplicate of #214

**Comment by nemihome** [comment] 2020-03-23 11:31
Year, the errors are still the same. Could be possible that this is connected to #214 because I'm also having more than 4000 photos

**Comment by skjnldsv** [comment] 2020-03-23 11:34
Let's close in favor of the other issues to help gather ressources :)
Thanks!

**Closed by skjnldsv** 2020-03-23 11:34 UTC
Labels: 0. Needs triage, bug, needs info
