### ISSUE TITLE
Link from Photos gallery shows maps of photos - not gallery NC18

### ISSUE THREAD

**Issue by rollanders** [nextcloud/photos#191] opened 2020-02-15 18:01 UTC
Click on Photos icon - all photos are shown in gallery view. Sharing not possible
Choose one album and those photos are shown in gallery view.  
Share this album.
Open the created link.
List of photos with miniatures are shown instead of gallery view.
I want to share the gallery view......, as in the previous version. 

NC 18.0.1

**Comment by nsteinmetz** [comment] 2020-02-16 18:39
Same issue here - we were sharing links to galleries which no longer works as expected.

**Comment by skjnldsv** [comment] 2020-02-24 09:22
duplicate of #128

**Closed by skjnldsv** 2020-02-24 09:22 UTC
