### ISSUE TITLE
Add some method to designate what folders/paths are included (or excluded)

### ISSUE THREAD

**Issue by snagglewest** [nextcloud/photos#209] opened 2020-02-25 21:29 UTC
Sort of a "feature request" and a gripe all in one.  

My request is to have some sort of mechanism to allow users to select what locations are included in the "photos" app display.

Ungraded to NC18 and to my surprise, found that the gallery replacement, photos, if used with the "external storage support" app, takes it upon itself to crawl every internal and external storage location and turn every graphic and video file into a thumbnail.  Nice...  NOT.  Like many users I would assume, I have a dedicated external share on the NAS for photos.  I also have several other shares with other various stuff including my entire video collection which is thousands of videos.  It would be great if there was some way to designate what path/folders user want included in the "Photos" screen.  I'm really not impressed with several thousand thumbnails of movie videos and misc stuff etc.   Sorry for the rant, I'm sure for some folks this is great, but for me it turned a useful app into something unusable.  At this point I've deactivated it with the hope it gets a update.

**Comment by skjnldsv** [comment] 2020-02-26 09:50
Duplicate of #141 :)

**Closed by skjnldsv** 2020-02-26 09:50 UTC
Labels: 0. Needs triage, enhancement
