### ISSUE TITLE
External Storage Video link 404 for preview

### ISSUE THREAD

**Issue by eephyne** [nextcloud/photos#1700] opened 2023-03-12 18:17 UTC
In the photo app, trying to watch video on the main page (all media) is working (video path is for exemple :
remote.php/dav//files/eephyne/Videosurveillance/leromantik/2023/2023-03-04/2023_03_04_10_50_15.mp4

but when navigating folder the link is 404 and look like that:
remote.php/dav//Videosurveillance/leromantik/2023/2023-03-04/2023_03_04_10_50_15.mp4

I have nextcloud 25.0.4 (linuxserver docker version, freshly installed one hour ago).

**Comment by joshtrichards** [comment] 2023-06-20 19:53
Duplicate of #1650

Hi @eephyne -Thanks for your report and additional details! If you agree that #1650 matches your report, please close this issue and subscribe yourself to #1650 to receive updates (since that's where further updates on this matter will likely be tracked). Also you can click the :+1: on #1650 to indicate you're impacted by the same situation (this assists the developers with prioritizing issues).

**Closed** 2023-06-20 19:55 UTC
