### ISSUE TITLE
Photos App seem to crash on HEIC files in NC 26.0.1

### ISSUE THREAD

**Issue by brievenbusalex** [nextcloud/photos#1765] opened 2023-04-25 22:41 UTC
**Describe the bug**
Since I upgrades from NC 24 via NC 25 to NC 26.0.1 the photos app seem to crash on HEIC files.

**To Reproduce**
In the files App I can preview HEIC files. I have ImageMagick with HEIC support installed and in NC 24 I could also preview and view the HEIC files in the photos app.
To reproduce the error I have created a new user with no shared or group folders, and have uploaded some images. As long as I don't upload HEIC files, I can preview/view all images/photos in both the files App as the Photos App. As I upload one HEIC in the files App and then goto the Photo app, it crashes (sometimes I see some photos and then they all disappear, no error is shown, just no visible photos anymore, a white screen, see below). 
In the browser console I can see errors, see below the browser log.

**Expected behavior**
In NC 24 I could preview/view HEIC files and view them in the Photos App aswell. In NC 26.0.1 it's not working anymore, I don't see photos in the Photo App if I have uploaded HEIC files.

**Screenshots**
![image](https://user-images.githubusercontent.com/10253686/234418295-66fc035c-b121-4de5-b86e-e1c8773f265e.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome, but same problem in other browsers

**Browser log**
In the browser console I see the following error:

(anoniem) @ main.js:39
ConsoleLogger.js:46 [ERROR] photos: Error fetching files {level: 2, app: 'photos', uid: 'test', error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at https://cloud.futu…}app: "photos"error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:3662409
    at Array.forEach (<anonymous>)
    at h.updateFiles (https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:3662222)
    at https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:2732297
    at https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:2733815
    at Array.forEach (<anonymous>)
    at https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:2733794
    at h._withCommit (https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:2735624)
    at h.commit (https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:2733768)message: "Unexpected end of JSON input"stack: "SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:3662409\n    at Array.forEach (<anonymous>)\n    at h.updateFiles (https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:3662222)\n    at https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:2732297\n    at https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:2733815\n    at Array.forEach (<anonymous>)\n    at https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:2733794\n    at h._withCommit (https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:2735624)\n    at h.commit (https://cloud.futureme.nl/apps/photos/js/photos-main.js?v=1e64db44-5:2:2733768)"[[Prototype]]: Errorconstructor: ƒ SyntaxError()message: ""name: "SyntaxError"[[Prototype]]: Objectconstructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()[[Prototype]]: Objectlevel: 2uid: "test"[[Prototype]]: Object
value @ ConsoleLogger.js:46
value @ ConsoleLogger.js:72
(anoniem) @ FetchFilesMixin.js:113

**Additional context**
I am running NC 26.0.1 on Almalinux 8.7 php 8.1.18

Server version: Apache/2.4.37 (AlmaLinux)

Package ImageMagick-1:6.9.12.86-1.el8.remi.x86_64 is installed.
Package ImageMagick-heic-1:6.9.12.86-1.el8.remi.x86_64 is installed.

**Comment by Rollbacke** [comment] 2023-04-26 08:57
Same problem here with a big library.
But, I don't know if it's HEIC files.

```
[ERROR] photos: Error fetching files 
Object { level: 2, app: "photos", uid: "user", error: SyntaxError }
ConsoleLogger.js:46:10
    value ConsoleLogger.js:46
    value ConsoleLogger.js:72
    r FetchFilesMixin.js:113
    l FetchFilesMixin.js:2
    x FetchFilesMixin.js:2
    b FetchFilesMixin.js:2
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    (Asynchrone : promise callback)
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    (Asynchrone : promise callback)
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    (Asynchrone : promise callback)
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    fetchFiles FetchFilesMixin.js:60
    getContent Timeline.vue:237
    VueJS 4
    needContent FilesListViewer.vue:244
    VueJS 4
    isNearBottom VirtualScrolling.vue:231
    VueJS 12
    resizeObserver VirtualScrolling.vue:260
    (Asynchrone : ResizeObserverCallback)
    mounted VirtualScrolling.vue:257
    VueJS 18
    init vue-router.esm.js:2980
    init vue-router.esm.js:2978
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    updateFiles files.js:2
    updateFiles files.js:2
    A vuex.esm.js:831
    commit vuex.esm.js:437
    commit vuex.esm.js:37
    _withCommit vuex.esm.js:601
    commit vuex.esm.js:36
    commit vuex.esm.js:394
    appendFiles files.js:142
    A vuex.esm.js:736
    dispatch vuex.esm.js:490
    dispatch vuex.esm.js:393
    r FetchFilesMixin.js:98
    l FetchFilesMixin.js:2
    x FetchFilesMixin.js:2
    b FetchFilesMixin.js:2
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    fetchFiles FetchFilesMixin.js:60
    getContent Timeline.vue:237
    VueJS 4
    needContent FilesListViewer.vue:244
    VueJS 4
    isNearBottom VirtualScrolling.vue:231
    VueJS 12
    resizeObserver VirtualScrolling.vue:260
    mounted VirtualScrolling.vue:257
    VueJS 18
    init vue-router.esm.js:2980
    init vue-router.esm.js:2978
FetchFilesMixin.js:114:12
    r FetchFilesMixin.js:114
    l FetchFilesMixin.js:2
    x FetchFilesMixin.js:2
    b FetchFilesMixin.js:2
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    (Asynchrone : promise callback)
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    (Asynchrone : promise callback)
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    (Asynchrone : promise callback)
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    fetchFiles FetchFilesMixin.js:60
    getContent Timeline.vue:237
    VueJS 4
    needContent FilesListViewer.vue:244
    VueJS 4
    isNearBottom VirtualScrolling.vue:231
    VueJS 12
    resizeObserver VirtualScrolling.vue:260
    (Asynchrone : ResizeObserverCallback)
    mounted VirtualScrolling.vue:257
    VueJS 18
    init vue-router.esm.js:2980
    init vue-router.esm.js:2978
```

**Comment by brievenbusalex** [comment] 2023-04-26 10:03
This issue is Fixed with https://github.com/nextcloud/photos/pull/1759 . I just manually installed the fix and it works,  I can view all photo's including HEIC files 👌 It will be deployed in 26.0.2. if you can't install it manually.

**Comment by coalwater** [comment] 2023-04-26 16:07
@brievenbusalex any instructions explaining how I could install the diff manually ?

**Comment by brievenbusalex** [comment] 2023-04-26 19:39
> @brievenbusalex any instructions explaining how I could install the diff manually ?

Probably the smartes option is to wait for release 26.0.2 (2023-05-19).

**Comment by umgfoin** [comment] 2023-04-26 23:57
duplicate of #1753

**Closed by umgfoin** 2023-04-26 23:57 UTC
Labels: bug, duplicate, 0. Needs triage
