### ISSUE TITLE
NC 18 JPG Images not loading when opened in a directory with special chars

### ISSUE THREAD

**Issue by tk7936** [nextcloud/photos#190] opened 2020-02-13 03:58 UTC
NC 18.01 RC2
Photos 1.0

When i open a jpg within a directory that contains NO special chars for example " ", "(", ")". "~" ect,
the image opens, if it DOES contain special chars the image viewer opens and just loads for ever without displaying the image.

**Comment by Kourai** [comment] 2020-02-25 11:10
Yep, same here, although I'm not sure if it trigger by " ", "(", ")". "~", or maybe by accent ("é", "è", "à" and all the lovely accent we french people use a lot!)

**Comment by Boki4d** [comment] 2020-04-23 16:32
I've reported an similar issue here:
https://github.com/nextcloud/photos/issues/301

**Comment by skjnldsv** [comment] 2020-04-24 09:43
We're talking about opening an image, right? Not browsing the photos in the Photos app, correct?

**Comment by tk7936** [comment] 2020-04-27 03:04
yes exactly

**Comment by skjnldsv** [comment] 2020-04-27 10:30
Duplicate of https://github.com/nextcloud/viewer/issues/415

**Closed by skjnldsv** 2020-04-27 10:30 UTC
Labels: 1. to develop, bug
