### ISSUE TITLE
Nextcloud 21.0.1 Photos not loading

### ISSUE THREAD

**Issue by axheli** [nextcloud/photos#739] opened 2021-04-10 02:22 UTC
Hello i just updated to nextcloud 21.0.1 and when i click on the photos tab via web it only populates a few and it stops i never had this issue before the app version is 1.3.0

what do you think about this @skjnldsv

**Comment by skjnldsv** [comment] 2021-04-12 07:20
Any errors in browser logs?

**Comment by axheli** [comment] 2021-04-12 12:22
Nope nothing so far. The safety to load for a little and then just stops loading the photos

**Comment by axheli** [comment] 2021-04-12 15:56
@skjnldsv so i installed PHP 8.0 and it seems to be working i think it has something to do with PHP 7.4

**Comment by skjnldsv** [comment] 2021-04-13 05:26
Hum, that is weird. Should not change anything.
But closing since we cannot reproduce :thinking:

**Closed by skjnldsv** 2021-04-13 05:26 UTC
Labels: 0. Needs triage, bug
