### ISSUE TITLE
Albums should show photos from oldest to newest

### ISSUE THREAD

**Issue by darguez** [nextcloud/photos#1427] opened 2022-10-26 11:44 UTC
When you see the photos in an album (think about a real printed album) you always want to start by the beginning. So the normal order should be from oldest photos to newest. Also the Slideshow should show oldest photos first.

**Comment by hansixxxx** [comment] 2022-11-03 13:39
I don´t understand why it isn´t possible to add a sort mechanism to the photos app? Can someone explain the technical problem?

**Comment by artonge** [comment] 2022-11-03 13:53
@hansixxxx There is no technical limitation for this issue. It is only human time limited. ;)

**Comment by artonge** [comment] 2022-11-08 13:32
Duplicate of https://github.com/nextcloud/photos/issues/1424

**Closed by artonge** 2022-11-08 13:32 UTC
Labels: bug, 0. Needs triage
