### ISSUE TITLE
Sort order for full screen pictures

### ISSUE THREAD

**Issue by EnergyFussl** [nextcloud/photos#1083] opened 2022-04-22 17:00 UTC
**Describe the bug**
When you are display photos in full screen on the browser the order of the pictures is different when you are naming the photos like following.
Image-1
Image-2
Image-3
Image-4
Image-5
Image-6
Image-7
Image-8
Image-9
Image-10
Image-11
…
Image-20
Image-21
...
Image-30
Image-31

When displaying in normal file viewer, they are correctly sorted, but when you are click on it to see it in full screen mode it is then sorted like
Image-1
Image-11
Image-12
…
Image-2
Image-20
Image-21
Image-3
Image-4
Image-5

And it depends on how far the count of the files is going.

Here you can see how the list order is in explorer
![2022-04-22 18_54_28-smal - Dateien - EnergyFussl Nextcloud](https://user-images.githubusercontent.com/29057246/164760823-06f7ab9a-96a4-41a7-b3cd-69105e20c767.png)

And here how it is displayed

![photo](https://user-images.githubusercontent.com/29057246/164760473-e5f46634-d424-482f-89ae-20d379c002bc.gif)

**Comment by umgfoin** [comment] 2022-07-06 10:11
Duplicate of #914

**Closed by umgfoin** 2022-07-06 10:11 UTC
Labels: bug, 0. Needs triage
