### ISSUE TITLE
Make it possible to handle the _file_ after selecting the image (copy, move, tag, ...)

### ISSUE THREAD

**Issue by grinapo** [nextcloud/photos#300] opened 2020-04-21 08:10 UTC
**Is your feature request related to a problem? Please describe.**
I browse the images. I find one or some I like. I want to copy images into an already existing folder, shared, public or else.

**Describe the solution you'd like**
Well, both #83 and #84 would offer an approach, but since Nextcloud is actually a file storage it seems logical to be able to copy or move a selected file. 

Possible solutions:

- another tab next to *Chat* and *Sharing*, which would offer file management functions, like *copy*, *move*, *tag*, or even helpers like *copy/move into an album*
- after implementing multiselect -- the same functions in whatever UI you pick to have then.
- suboptimal, but still better than nothing: a button to jump to the file in the storage. (I'm not sure it's even possible easily.)

**Comment by skjnldsv** [comment] 2020-04-25 18:00
Duplicate of https://github.com/nextcloud/viewer/issues/7 I guess :)

**Closed by skjnldsv** 2020-04-25 18:00 UTC
Labels: 0. Needs triage, enhancement
