### ISSUE TITLE
Photos dont load. Neither in App nor in Web.

### ISSUE THREAD

**Issue by carlchen2007** [nextcloud/photos#1768] opened 2023-04-30 17:19 UTC
When i try to scroll threw my photos in the nextcloud app it only displays a handful images, the rest is a placeholder. When i try to use photos in the web, it first shows a grid and then gets blank. I already rebooted and tried on different devices and browsers but neither worked. Info: My Nextcloud runs behind a reverse proxy and on an ubuntu 22.04 vm.

**To Reproduce**
1. go to Photos in the the Nextcloud
2. See a grid
3. watch the page go blank

**Expected behavior**
It should have just shown me my pictures

**Screenshots**
![image](https://user-images.githubusercontent.com/119757558/235366598-4497768a-04dd-481f-ac4e-88d4189ed8a9.png)
![image](https://user-images.githubusercontent.com/119757558/235366763-8908d66b-d742-471b-9c1e-aab37e312c2e.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version 16.4

**Smartphone (please complete the following information):**
 - Device: Nokia7.2
 - OS: Android 11
 - Browser Mozilla Firefox

Browser Logs
[Error] Failed to load resource: the server responded with a status of 404 () (icons.css, line 0)

[Log] JQMIGRATE: Migrate is installed, version 3.4.0 (core-common.js, line 2)

[Warning] Proxying an event bus of version 3.0.2 with 1.3.0 (core-common.js, line 2)

[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Warning] $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Warning] Proxying an event bus of version 3.0.2 with 1.3.0 (core-common.js, line 2)

[Debug] OCA.Files.Sidebar initialized (files-sidebar.js, line 2)

[Debug] OCA.Files.Sidebar initialized (files-sidebar.js, line 2)

[Warning] Proxying an event bus of version 3.0.2 with 1.3.0 (core-common.js, line 2)

[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Warning] $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Debug] OCA.Comments.View initialized (comments-comments-app.js, line 2)

[Warning] Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 (core-main.js, line 2)

[Warning] Proxying an event bus of version 3.0.2 with 1.3.0 (core-common.js, line 2)

[Warning] Proxying an event bus of version 3.0.2 with 1.3.0 (core-common.js, line 2)

[Debug] OCA.Sharing.ShareSearch initialized (files_sharing-files_sharing_tab.js, line 2)

[Debug] OCA.Sharing.ExternalLinkActions initialized (files_sharing-files_sharing_tab.js, line 2)

[Debug] OCA.Sharing.ExternalShareActions initialized (files_sharing-files_sharing_tab.js, line 2)

[Warning] Proxying an event bus of version 3.0.2 with 1.3.0 (core-common.js, line 2)

[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Warning] $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Error] error in loadState:  – Error: Could not find initial state config of libresign

Error: Could not find initial state config of libresign
	(anonyme Funktion) (libresign-tab.js:2:1496124)
	(anonyme Funktion) (libresign-tab.js:2:1584445)
	Globaler Code (libresign-tab.js:2:1584449)
[Error] error in loadState:  – Error: Could not find initial state config of libresign

Error: Could not find initial state config of libresign
	(anonyme Funktion) (libresign-tab.js:2:1505220)
	(anonyme Funktion) (libresign-tab.js:2:1584445)
	Globaler Code (libresign-tab.js:2:1584449)
[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Warning] [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config – Object (viewer-main.js, line 2)

Object
[Debug] OCA.Viewer initialized (viewer-main.js, line 2)

[Warning] Proxying an event bus of version 3.0.2 with 1.3.0 (richdocuments-viewer.js, line 2)

[Warning] oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20 (core-main.js, line 2)

[Warning] Proxying an event bus of version 3.0.2 with 1.3.0 (deck-reference.js, line 2)

[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Warning] jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Warning] Proxying an event bus of version 3.0.2 with 1.3.0 (core-common.js, line 2)

[Info] session heartbeat disabled (core-main.js, line 2)

[Warning] Proxying an event bus of version 3.0.2 with 1.3.0 (notifications-vendors-node_modules_nextcloud_initial-state_dist_index_esm_js-node_modules_nextcloud_moment_-4efa53.js, line 2)

[Warning] $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Debug] Registering notifications container as a menu (notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js, line 2)

[Warning] $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Warning] $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. (core-main.js, line 2)

[Debug] Notifications permissions granted (notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js, line 2)

[Debug] Polling interval updated to 30000 (notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js, line 2)

[Debug] Did not start background fetcher as session_keepalive is off (notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js, line 2)

[Debug] Got notification data (notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js, line 2)

[Debug] Polling interval updated to 30000 (notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js, line 2)

[Debug] Did not start background fetcher as session_keepalive is off (notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js, line 2)

[Error] [ERROR] photos: Error fetching files – Object

Object
	value (photos-main.js:2:320916)
	value (photos-main.js:2:321380)
	(anonyme Funktion) (photos-src_mixins_FetchFilesMixin_js.js:2:21287)
	l (photos-src_mixins_FetchFilesMixin_js.js:2:11860)
	(anonyme Funktion) (photos-src_mixins_FetchFilesMixin_js.js:2:13194)
	k (photos-src_mixins_FetchFilesMixin_js.js:2:19308)
	a (photos-src_mixins_FetchFilesMixin_js.js:2:19512)
[Error] SyntaxError: JSON Parse error: Unexpected EOF

	(anonyme Funktion) (photos-src_mixins_FetchFilesMixin_js.js:2:21332)
	l (photos-src_mixins_FetchFilesMixin_js.js:2:11860)
	(anonyme Funktion) (photos-src_mixins_FetchFilesMixin_js.js:2:13194)
	k (photos-src_mixins_FetchFilesMixin_js.js:2:19308)
	a (photos-src_mixins_FetchFilesMixin_js.js:2:19512)

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by ekuraev** [comment] 2023-05-01 11:18
Same issue.  Nextcloud Hub 4 (26.0.1) setup in Docker (AIO)

Desktop Safari/Chrome 
Mobile IOS.

**Comment by carlchen2007** [comment] 2023-05-01 14:08
I am using Apache and Ubuntu 22.04

**Comment by carlchen2007** [comment] 2023-05-01 14:08
And I am using a reverse proxy

**Comment by christophecasson** [comment] 2023-05-01 23:11
Same issue on 26.0.1 (ubuntu 22.04 up-to-date)
- Brave browser on macos
- Images do not load either on "media" tab of iOS app
However, Memories and Files "apps" on web works well...

**Comment by FernandoMarques-Santos** [comment] 2023-05-02 09:28
Same issue on Ubuntu 20.04.6

**Comment by dewomser** [comment] 2023-05-02 12:02
Same issue. Nextcloud Hub 4 (26.0.1)
All browsers
Debian Buster / x86_64
4096 MiB
PHP (FPM) 8.1

**Comment by rzech** [comment] 2023-05-02 12:32
Same issue in all browsers
Videos are shown when clicking on "Videos" (but not perview icon)
When clicking on "All Media" or "Photos" I get a blank page

Nextcloud Hub 4 (26.0.1)
Ubuntu 22.04.02
PHP (FPM) 8.1

**Comment by clorenz150** [comment] 2023-05-02 14:24
Same issue.
Viewing by folder works with some missing folder previews.

Debian 11.5
Apache/2.4.56 (fpm-fcgi)
PHP version: 8.1.18
Nextcloud: 26.0.1

**Comment by sergiorsmaster** [comment] 2023-05-02 15:55
Same issue in all browsers after update Recognize app to 4.0.1.
Nexcloud Hub 4 26.0.1 docker setup.

**Comment by umgfoin** [comment] 2023-05-04 00:12
duplicate of https://github.com/nextcloud/photos/issues/1753

**Closed by umgfoin** 2023-05-04 00:12 UTC
Labels: bug, duplicate, 0. Needs triage
