### ISSUE TITLE
Add option "Set as album cover" for images inside albums.

### ISSUE THREAD

**Issue by luckkmaxx** [nextcloud/photos#1987] opened 2023-08-05 11:15 UTC
**Is your feature request related to a problem? Please describe.**
When you create an album, the cover is taken randomly which many times is the worst one from the album. 

**Describe the solution you'd like**
Adding this option will let users to identify better their albums, and set a more relevant image that matches the album title.

**Comment by joshtrichards** [comment] 2023-08-06 14:16
Hi @luckkmaxx - Great suggestion and I don't think you're alone! This looks to be a duplicate of #1593. If you agree, give that issue a :+1: and close this Issue out to avoid confusion. Thanks!

P.S. You may also want to subscribe yourself to that issue to be informed about progress.

**Closed** 2023-08-06 19:28 UTC
Labels: enhancement, 0. Needs triage
