### ISSUE TITLE
More beautiful photo view

### ISSUE THREAD

**Issue by grenzverkehr** [nextcloud/photos#496] opened 2020-10-17 11:33 UTC
Thank you very much for the implementation of the [new photo view](https://github.com/nextcloud/photos/pull/435). Here the photos are presented uncut. And that is good and right. But unfortunately it does not yet meet my requirements as a photographer. This has two reasons: On the one hand, the photos are presented clearly too small. Secondly, the square grid view does not meet my aesthetic requirements. Most photo platforms solve this better: here the photos are presented much bigger and more beautiful. Just to name a few: CC Search, Flickr, Google Photos, Amazon Photos, Microsoft Photos, Adobe Stock, Getty Images, 123RF, Shutterstock, pixabay, Photocase

It would be nice if Nextcloud Photos would also have the possibility to present photos in a large format. Instead of 7 photos in a row as now, only 3 photos in landscape format – on a Full HD monitor.

Here two views for comparison: CC Search and the new Nextcloud Photos view.

![cc_search](https://user-images.githubusercontent.com/50242159/96335769-3c159000-107b-11eb-9b28-5137a010ceec.png)

![nextcloud_photos](https://user-images.githubusercontent.com/50242159/96335773-433c9e00-107b-11eb-87d9-9ac994aa4585.png)

**Comment by dennorske** [comment] 2020-10-17 12:02
I totally agree, in addition there's too much unused space currently.

**Comment by Mikescops** [comment] 2020-10-17 12:18
Sorry it doesn't met your "requirements", if you're a photographer as you say, you should use dedicated tools like the open source http://www.darktable.org/! 

The community projects like Nextcloud are not here to met "your" requirements but various number of users. 

Please consider better wording in the future, your current request may be offensive for the contributors.

@skjnldsv @jancborchardt FYI

**Comment by grenzverkehr** [comment] 2020-10-17 13:08
Please excuse my choice of words. I didn't mean to offend anyone. I just wanted to make a suggestion for another (from my point of view better and more beautiful) photo view.

**Comment by jancborchardt** [comment] 2020-10-22 15:02
Some points here:
- We already have 2 different views, do we really want to add a 3rd one? Remember, all these have to be maintained, and normal people don’t change the default anyway
- The drawback of the view you show @grenzverkehr is that while landscape photos are shown larger, portrait photos are comparably smaller.
- The non-cropped view isn’t particularly beautiful, which is also why we went with the cropped one by default

**Comment by skjnldsv** [comment] 2020-10-23 08:51
> * We already have 2 different views, do we really want to add a 3rd one? Remember, all these have to be maintained, and normal people don’t change the default anyway

Agree too, I think those two are enough for now.

**Comment by pdroalves** [comment] 2020-11-05 10:17
I support this issue, since I agree that current views lack good taste. The project could attract attention of people interested on organizing their photo library if we have a more modern way of presenting photos than current soulless-cropped option.

By the way, I don't see the problem with their choice of words. Probably it's a translation confusion and I don't see a reason to be rude with they =)

**Comment by dlauper** [comment] 2020-11-15 18:21
Regarding the wording, I see how it can be taken as offense : )

But from a design point of view, I agree 100% percent with @grenzverkehr , probably not a surprise for one or the other, as I have promoted this kind of grid in my [community post](https://help.nextcloud.com/t/ideas-for-revolutionary-photo-organization/89278). 
It was even already suggested in #146 in a comment by @janis91, and @jancborchardt , you seemed more open to the idea then and even encouraged @janis91 to continue?

Regarding portrait and landscape pictures, I may have an idea (and another example of this filled view): Pixieset does it as described by @grenzverkehr but in columns.
![image](https://user-images.githubusercontent.com/11159094/99192941-047f2e00-2776-11eb-8163-077f6567f2c3.png)

Can this filled grid view be coded in a way, that columns (as pixieset) and lines (cc search and others) are essentially identical? This would help with the effort of maintaining them. 

So, my suggestion would be:
- cropped view
- filled lines
- filled columns

with one toggle button for switching between them, and making it a permanent setting for each album. So the user can switch easily and set the most optimal view for each album.

**Comment by skjnldsv** [comment] 2020-11-16 06:38
Hey! So, I'll take a final statement here for clarification :)

On nextcloud 21  we implemented the non-cropped view per community request (same design as macOs photos :wink:)
![localhost_8080_index php_apps_photos_](https://user-images.githubusercontent.com/14975046/99220002-185e7a80-27de-11eb-84c5-ec4a57e21c86.png)

Currently, there is no plan from us to implement a third view (fitted columns) as this is far from our priorities (photos users have higher priority requests so far). Nonetheless, if anyone wants to implement this view, we would be fine for it, but the work is really considerable. You need a 100% fully working virtual scroller that supports this layout as well as date separators (no features regressions allowed). So far I don't think there is an available library that does that.

I will therefore close this issue for now, as more discussions will not add anything and unless someone else (community) wants to seriously dive into it, which we'll be happy to assist, we will not spend time on implementing the fitted columns so far. Maybe one day, in which case we'll re-open, but not for now :)

Hope everyone will understand :wink: :hugs: 
Take care,
John

**Closed by skjnldsv** 2020-11-16 06:38 UTC
Labels: 0. Needs triage, design, enhancement, low
