### ISSUE TITLE
Edit via fullscreen broken

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/photos#2540] opened 2024-07-09 11:37 UTC
**Describe the bug**
![no_file_type](https://github.com/nextcloud/photos/assets/1315170/cd75a1d6-02b8-48c9-b2b4-ccf0f99f919d)

fullscreen closes, clicking on the image again repeatedly just shows the top-right error until you do a full-refresh of the page

**Expected behavior**
open editor or hide edit option when lacking permissions or show error that permissions are lacking

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win11Pro
 - Browser [e.g. chrome, safari] Ff
 - Version [e.g. 22] 127.0.1

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by jancborchardt** [comment] 2024-07-09 11:48
cc @sorbaugh – maybe @skjnldsv since you worked on the editor?

**Comment by sorbaugh** [comment] 2024-07-09 12:05
Also cc-ing @artonge

**Comment by skjnldsv** [comment] 2024-07-09 12:47
Duplicate of https://github.com/nextcloud/photos/issues/2516
Duplicate of https://github.com/nextcloud/server/issues/45484
Duplicate of https://github.com/nextcloud/viewer/issues/2323

**Closed** 2024-07-09 12:47 UTC
Labels: bug, 0. Needs triage, regression

**Comment by AndyScherzinger** [comment] 2024-07-09 14:00
Didn't spot the duplicates, Sry!

**Comment by RyoKub** [comment] 2024-07-19 15:54
I have updated Nextcloud 29.0.3. This issue is still not fixed. It is a pity. It is a good app. I hope someone kind will fix it soon.
