### ISSUE TITLE
'Error Loading' jpg from Photos 2.0 album view

### ISSUE THREAD

**Issue by Wizlonex** [nextcloud/photos#1470] opened 2022-11-10 19:40 UTC
**Describe the bug**
1.  Displays 'Error loading {name}.jpg' for a photo album shared via "public link"
2.  Requires a login at a prompt from the shared "public link" in order to download the shared files
  ==> This defeats the purpose of having a 'shared public link'

** To Reproduce **
In Nextcloud Hub 3 25.01:

Create an Album, add photos to the album (you can just add the stock photos)
Create a "shared public link" for the album you created and copy the link e.g. to clipboard
Access the album via the shared link via e.g. an Incognito Mode browser or some other other seperate browsing session.
You get a nice thumbnail view of the album - thumbnails display just fine - no problems so far, but...
Click on any photo in the album via the 'public shared link'
==> 'Error loading {name.jpg|' is displayed for all pictures, even the stock ones pre-installed via Nextcloud.

Continuing:
From one of the the 'Failed to load' screens, click on the Download button.
==>  Nextloud asks for login credentials.
    ==> if credentials are entered, the photo can in fact be downloaded, but it defeats the point of having a 'public link'

I have tried this on two separate VM installs, and also after upgrading a long-time working Nextcloud container running on Ubuntu 20.04 (my 'production server') - they all fail in the same manner, so I am wondering if this time, it's not actually me doing something dumb again.  :-)

**Expected behavior**
1.  Click on the thumbnail, and a larger image appears.
2.  Click on the download button, and it downloads the photo(s) without the need for any credentials

**Screenshots**
How the album looks via the link - all is good:
![Screenshot from 2022-11-10 14-30-35](https://user-images.githubusercontent.com/35621692/201189437-43632fc6-346a-4e2c-a0de-202d535577b6.png)

Now click on a photo, and you immediately get this error:
![Screenshot from 2022-11-10 14-30-49](https://user-images.githubusercontent.com/35621692/201189456-3306e6ec-3834-4be3-b977-f28a8b548289.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - ALSO - same error is obtained via browser on an Android phone
 - Browser - Chrome, Google Chrome and Firefox (and Chrome on Android phone)
 - Desktop Chrome Version 107.0.5304.110 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```
# Chrome
Refused to apply style from 'https://cloud.ogselfhosting.com/apps/photos/css/icons.css?v=d233662f-9' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.0
ProxyBus.ts:11 Proxying an event bus of version 2.1.1 with 3.0.2
e @ ProxyBus.ts:11
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
ConsoleLogger.js:60 [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config Object
value @ ConsoleLogger.js:60
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
t @ index.es.js:2337
index.js:19 Proxying an event bus of version 2.1.1 with 3.0.2
e @ index.js:19
2globals.js:60 oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20
tn @ globals.js:60
ProxyBus.ts:16 Proxying an event bus of version 2.1.1 with 3.0.2
e @ ProxyBus.ts:16
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
ProxyBus.ts:16 Proxying an event bus of version 2.1.1 with 3.0.2
e @ ProxyBus.ts:16
2globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
tn @ globals.js:60
3globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
tn @ globals.js:60
session-heartbeat.js:103 session heartbeat polling started
ConsoleLogger.js:64 [ERROR] photos: SW registration failed:  Object
value @ ConsoleLogger.js:64
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
tn @ globals.js:60
Mo4vdiwWwKEBCIhlaAsUnqVTI2o0RDTY:1 Refused to apply style from 'https://cloud.ogselfhosting.com/apps/photos/css/icons.css?v=d233662f-9' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Additional context**
I don't think this is a browser issue, I believe it's a bug in Photos 2.0.  I really appreciate the work you are doing to make Photos much more usable so THANK YOU VERY MUCH.  Hopefully this is of some value - given that I have the failure on three different installs (one of them being my 'production server'), I thought this might be a real bug vs admin-error on my part.

I would be happy to share any of my server config files too if they are helpful?  I get the same error via an aold installation on Ubuntu 20.04 and a new one on Ubuntu 22.04 (different php versions etc.).

V/R

Andrew

**Comment by xamindar** [comment] 2022-11-11 15:20
Confirmed issue in my server as well. Version 25.0.1.

**Comment by Lartza** [comment] 2022-11-11 15:23
Duplicate of #1452

**Closed by Lartza** 2022-11-11 15:23 UTC
Labels: bug, 0. Needs triage
