### ISSUE TITLE
Photos for public links

### ISSUE THREAD

**Issue by schaze** [nextcloud/photos#128] opened 2020-01-18 16:57 UTC
With Nextcloud 18 and Photos app there is no preview popup any more for pictures in folder share by link. When clicking a picture, always the download function is triggered. With this there is basically no real image gallery sharing possible any more.
In Nextcloud 17 with the gallery app there was a preview popup and a slideshow option also for shared folders.

Please bring that back. I love how fast the new photos app is (order of magnitude faster than in nc17) but image preview is a basic funtction I really cannot miss (or rather the rest of my family wanting to see the images of my daughter)

**Server configuration detail**

Operating system: Linux 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64

Webserver: Apache/2.4.38 (Debian) (apache2handler)

Database: mysql 10.4.11

PHP version: 7.3.13

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

Nextcloud version: 18.0.0 - 18.0.0.10

Updated from an older Nextcloud/ownCloud or fresh install: updated from 17.0

Where did you install Nextcloud from: Docker deployed on kubernetes 1.17.0

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.4.0
 - calendar: 2.0.0
 - carnet: 0.19.2
 - cloud_federation_api: 1.1.0
 - cms_pico: 1.0.4
 - comments: 1.8.0
 - dav: 1.14.0
 - encryption: 2.6.0
 - external: 3.5.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.1
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 1.0.2
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - activity
 - admin_audit
 - bruteforcesettings
 - contacts
 - files_rightclick
 - user_ldap
</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "htaccess.RewriteBase": "\/",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE**",
        "nextcloud"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "forwarded_for_headers": [
        "X-Forwarded-For",
        "HTTP_X_FORWARDED_FOR"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.0.10",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "3306",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "theme": "",
    "loglevel": 2,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE**",
    "overwriteprotocol": "https",
    "mysql.utf8mb4": false,
    "app_install_overwrite": [
        "text"
    ],
    "has_rebuilt_cache": true
}

</details>

External storages: yes

<details><summary>External storage configuration</summary>

No mounts configured

</details>

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

**Comment by skjnldsv** [comment] 2020-01-18 18:47
Hello!
I'm not sure I understand, what do you mean by a preview popup? You mean opening the slideshow view on click?
Or you mean having the photo layout on 'public' pages?

**Comment by schaze** [comment] 2020-01-18 20:04
Hi,
sorry for beeing unclear. 
I do get thumbnails in the shared folder but not the slideshow view. If what you mean with slideshow view is this the one looking like this:
![Screenshot from 2020-01-18 21-02-52](https://user-images.githubusercontent.com/4409163/72669760-0ed97a00-3a36-11ea-9c27-943f86863b6c.png)

**Comment by mikweb2017** [comment] 2020-01-18 20:17
i have same  problem  
![Bildschirmfoto 2020-01-18 um 21 14 57](https://user-images.githubusercontent.com/30271757/72669899-c327d000-3a37-11ea-9206-1a58a63c6808.png)
if I click on a photo it does not appear as a preview popup

**Comment by schaze** [comment] 2020-01-18 20:24
@mikweb2017 : that is not the same problem as mine. My preview popup works in a normal photo page - I only have the issue when opening a photo in a shared folder (open via the share link).

**Comment by skjnldsv** [comment] 2020-01-19 15:12
@mikweb2017 please open a separate issue :)

**Comment by skjnldsv** [comment] 2020-01-19 15:12
> Instead I get this for the shared folder when accessing it via the share link:

Ah, ok!
Yes, photos is not handling public links yet :)

**Comment by menaceone** [comment] 2020-02-01 19:42
Hey folks, 
I really miss that feature as well. If any help for testing etc. is needed just ping me.
greetings

**Comment by Sandman0984** [comment] 2020-02-04 17:55
Hi,
I would like to see this feature added to Photos as well!  Just like @menaceone , I'll help with testing if you need it.  Keep up the good work!  Thank you!

**Comment by knrd1** [comment] 2020-02-04 20:19
Hey,
I agree with the previous comments, in my humble opinion this was the most important Nextcloud's functionality. At this moment I can't share the gallery with anyone... Unless they agree to download each file...
Thanks!

**Comment by Englbrechtful** [comment] 2020-02-05 05:56
Agreed, this is a very important functionality. Could the devs please comment on an ETA to fix this? Need to know if it makes sense to downgrade NC or if we can wait for a fix. 
Thank you

**Comment by grenzverkehr** [comment] 2020-02-09 17:32
This problem has nothing to do with "Photo" but with the fact that the "gallery slideshow" no longer exists (https://github.com/nextcloud/viewer/issues/89#issuecomment-576665434). If the problem is indeed only solved with the release of version 19, version 18 will remain useless for many people.

**Comment by hezten** [comment] 2020-02-10 15:06
Can anyone point me to a guide to downgrade to nextcloud 17 ? nextcloud 18 is useless for me without this feature

**Comment by quatze** [comment] 2020-02-11 11:31
Same for me. This was one of the key features, when using nextcloud to share photos with family and friends. Would also love if anyone could point out how to downgrade to version 17.

**Comment by hroling** [comment] 2020-02-13 20:10
This is really a big disappointment that the slideshow is not working in NC18 and the Photo app. I will skip NC18 and wait for NC19. 

This is the first time i'm not glad with the new version since owncloud 5.

**Comment by Aesculapius** [comment] 2020-02-16 18:43
Same here, useless if without. How can such decision be made, as this clearly is a much used feature?

**Comment by mwllgr** [comment] 2020-02-17 20:13
Hi, same for me - please fix/add that feature again. Photo preview/slideshow in public links is a pretty useful feature for many users!

**Comment by fuco809** [comment] 2020-02-18 19:30
we too used the "shared as link" gallery public view links, which are not implemented in photos yet. please bring back that feature.

**Comment by FanchTheSystem** [comment] 2020-02-19 15:30
+1

Maybe nextcloud 18 should not have been in stable release channel...

**Comment by x42** [comment] 2020-02-19 20:31
Is this being actively worked on?

**Comment by kev300** [comment] 2020-02-20 17:24
Is there a chance that this important feature is also back ported to 18.0.2 or 3?
I don't want to wait until 19.. It really sucks that features are silently dropped without mentioning in the change log. :(

**Comment by nursoda** [comment] 2020-02-21 05:44
Folks…I think it would be sufficient to express feelings (support a claim by adding a thumbs-up) and to subscribe to the bug. I don't think 100 comments will speed up implementation. This still is a community effort. This speaking as non-dev, also waiting.

The NC dev mistake I see is that the app has been replaced by a newly developed one without proper notice to users that an important functionality is still missing AND without the option to use the old app for the time being.

**Comment by szaimen** [comment] 2020-02-21 13:22
FYI: https://github.com/nextcloud/photos/issues/154#issuecomment-589627542

**Comment by hroling** [comment] 2020-02-21 15:26
> 
> 
> FYI: [#154 (comment)](https://github.com/nextcloud/photos/issues/154#issuecomment-589627542)

Thanks, it is working on my NC18 testserver

**Comment by Sandman0984** [comment] 2020-02-21 21:00
> FYI: [#154 (comment)](https://github.com/nextcloud/photos/issues/154#issuecomment-589627542)

This worked for me as well.  Thank you!  I'll still be looking for this feature in Photos as well, hopefully by NC19.  Again, let me know if I can help with testing Photos in future releases.

**Comment by jospoortvliet** [comment] 2020-02-28 11:59
FYI, we are trying to fix this and other regressions asap. This was an oversight that even the testing during beta and rc didn't catch - sorry for that, lucky news is that you can get involved in testing to help avoid these issues next time!

See https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/32 for a more complete response.

**Comment by hroling** [comment] 2020-02-28 14:27
> 
> 
> FYI, we are trying to fix this and other regressions asap. This was an oversight that even the testing during beta and rc didn't catch - sorry for that, lucky news is that you can get involved in testing to help avoid these issues next time!
> 
> See https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/32 for a more complete response.

Thanks Jos. I really appreciate that.

**Comment by jospoortvliet** [comment] 2020-03-02 18:36
@hroling thank hard workers like @skjnldsv - he already fixed, I think, all of the problems! Deadline is soon, RC coming this week (Thursday, most likely). We'd all appreciate it if you and others were willing to help test that RC so we can get 18.0.2 as stable as possible!

**Comment by menaceone** [comment] 2020-03-07 13:10
I just upgraded my docker container to `18.0.2RC1-apache`. 
Unfortunately behaviour has not changed. 
Still download dialog instead of Gallery view when clicking on a photo in a public link.

**Comment by nursoda** [comment] 2020-03-07 13:26
…and 18.0.2RC1 is not offered as beta update (yet).

**Comment by skjnldsv** [comment] 2020-03-09 09:23
Yep, not part of 18.0.2RC1 yet

**Comment by hroling** [comment] 2020-03-14 13:21
NC test-server upgraded to 18.0.2 but unfortunately no solution yet. I will wait for next update.

**Comment by szaimen** [comment] 2020-03-14 13:24
It will become available with 18.0.3

**Comment by skjnldsv** [comment] 2020-03-16 08:34
Yes, sorry about this :)
Small delay in time, this have been merged and is part of the upcoming 18.0.3 release https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/40?u=skjnldsv

**Closed** 2020-03-16 08:34 UTC
Labels: 1. to develop, enhancement, high, regression

**Comment by hroling** [comment] 2020-03-16 08:56
Thanks. I will test it if the beta/rc's of NC 18.0.3 are ready.

**Comment by jhesketh** [comment] 2020-03-23 03:17
Running today's daily build, the file no longer prompts to download but still won't display.

Firefox's console gives me the following:

```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 3 content-script.js:40:65
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. addStylesClient.js:220:17
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 2 globals.js:66:15
OCA.Viewer initialized Viewer.js:41:10
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). getInferredName.js:6:19
TypeError: "OCA.Text is undefined"
    data RichWorkspace.vue:75
    VueJS 6
        Me
        _data
        _n
        _n
        _init
        a
    render files.js:188
vue.esm.js:1897:12
    VueJS 8
        We
        Je
        Ve
        _data
        _n
        _n
        _init
        a
    render files.js:188
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
The humanFileSize library is deprecated! It will be removed in nextcloud 19. globals.js:66:15
The humanFileSize library is deprecated! It will be removed in nextcloud 19. globals.js:66:15
The humanFileSize library is deprecated! It will be removed in nextcloud 19. globals.js:66:15
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 5 globals.js:66:15
The humanFileSize library is deprecated! It will be removed in nextcloud 19. globals.js:66:15
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
Opening the viewer with a single string parameter is deprecated. Please use a destructuring object instead OCA.Viewer.open({ path: '/IMG_<REDACTED>.jpg' }) Viewer.js:97:11
Opening viewer for file  /IMG_<REDACTED>.jpg Viewer.vue:211
Error: "Request failed with status code 401"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
Viewer.vue:383
    t Viewer.vue:383
    c runtime.js:45
    _invoke runtime.js:271
    t runtime.js:97
    H viewer.js:355
    a viewer.js:355
```

The 401 error is likely the problem. I can also see the response code from nextcloud server as 401. This could be a bug with the server, but I think the path for the full sized image is wrong.

The page does load, as do the thumbnails, it is just the full sized view that fails.

**Comment by skjnldsv** [comment] 2020-03-23 07:20
> Running today's daily build, the file no longer prompts to download but still won't display.

Hey :)
What do you mean by today's build?

**Comment by nursoda** [comment] 2020-03-23 07:33
Probably https://download.nextcloud.com/server/daily/ ?

**Comment by jhesketh** [comment] 2020-03-23 07:37
Yes, `https://download.nextcloud.com/server/daily/latest.tar.bz2`

**Comment by skjnldsv** [comment] 2020-03-23 07:38
Let me try and see what is bugged :)
Thanks for testing!

**Comment by skjnldsv** [comment] 2020-03-23 07:57
Just tested, works fine for me with the default archive you linked :)
![Kazam_screencast_00000](https://user-images.githubusercontent.com/14975046/77294284-4a1d5100-6ce4-11ea-8f53-728d2e47290d.gif)

**Comment by jhesketh** [comment] 2020-03-23 09:38
Thanks so much for testing. Not sure what I am doing then that causes it not to work.

Here is the log for the file request:

`app_1            | 172.30.0.2 - 5r8NP******AKzB [23/Mar/2020:09:31:22 +0000] "PROPFIND /public.php/webdav/IMG_2019****_21****.jpg HTTP/1.1" 401 1055 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"`

Does that URL look correct for an image inside a folder?

If you still have your test instance running, are you able to tell if there are any errors in your console log?

Thanks :-)

**Comment by skjnldsv** [comment] 2020-03-23 09:40
I could reproduce your `RichWorkspace` error, and pinged the dev in charge.
But this is not related to this issue :)

Did you forbid the download of files in your share?
Maybe there is a permission error on the file?
Anything in your nextcloud.log?

**Comment by jhesketh** [comment] 2020-03-23 09:54
I have the same issue with or without forbidding downloads. As well as via email shares and link shares. I have not confirmed user shares, but I /think/ they are working (but with read/write/all perms).

The image loads fine in the viewer for my user, so I don't think it's a filesystem permission.

I can't see anything in the nextcloud log either.

**Comment by skjnldsv** [comment] 2020-03-23 10:00
Have you cleared your cache (just in case)
Are you opening the link share into your browser in private mode? Or are you logged in already?

Can you maybe send the link to skjnldsv@protonmail.com?

**Comment by jhesketh** [comment] 2020-03-23 10:02
I've ran `occ files:cleanup` with no obvious effect. I've tested viewing them in firefox private mode and chromium incognito (both new sessions) with the same result.

Thanks for helping debug. I'll share a test folder with you.

**Comment by skjnldsv** [comment] 2020-03-23 12:12
It looks like you're still having the old viewer.
Could you share the info.xml file of the viewer app?

**Comment by jhesketh** [comment] 2020-03-23 12:16
Oh, okay. I may have set it up incorrectly in docker then.

https://gist.github.com/jhesketh/b34fc3abce5fd488bc2512c1f9976f6c

The version in nextcloud settings is:
`Nextcloud 18.0.2 Build:2020-03-13T23:01:51+00:00 17722835c0b0f2bbd62bf4fd09a167985f921202`

I hadn't looked at this before. Is that the correct version for a daily build given the date is 10 days old?

**Comment by jhesketh** [comment] 2020-03-23 12:22
Hmm, looking at the daily tar, it seems like I may not have installed it into the docker image correctly. This seems to be a problem on my end. Thank you very much for the help, I'll continue to debug my setup!

**Comment by hroling** [comment] 2020-03-23 12:22
Latest version of 18.0.3 installed on my test server and works good.

**Comment by skjnldsv** [comment] 2020-03-23 12:30
> `Nextcloud 18.0.2 Build:2020-03-13T23:01:51+00:00 17722835c0b0f2bbd62bf4fd09a167985f921202`

Like mentionned :wink: 

> Yes, sorry about this :)
> Small delay in time, this have been merged and is part of the upcoming 18.0.3 release [help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/40?u=skjnldsv](https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/40?u=skjnldsv)

**Comment by skjnldsv** [comment] 2020-03-23 12:31
Thanks everyone for testing! It seems that all is well then!
Enjoy the incoming nc version! :rocket: 

Remember We love some more feedback on how you view the future of this app (search existing issues before :wink:)! :hugs:

**Comment by hroling** [comment] 2020-03-23 14:06
If I share a directory with photo's I don't see it in the shared albums. Is that correct?

![afbeelding](https://user-images.githubusercontent.com/7841958/77324771-8ae28d80-6d17-11ea-986e-ad458256b9bc.png)

**Comment by skjnldsv** [comment] 2020-03-23 14:10
No, it's photos that are shared with you

**Comment by hroling** [comment] 2020-03-23 14:58
> 
> 
> No, it's photos that are shared with you

Thanks. That was nog really clear.... :)

**Comment by ainola** [comment] 2020-03-24 03:51
Hm, I'm still getting downloads with 18.0.3 and a public share link. Should I be doing anything other than merely updating?

**Comment by skjnldsv** [comment] 2020-03-24 07:45
Yep, sorry,  18.0.3 is an unexpected security update.
18.0.4 it is :)

**Comment by jhesketh** [comment] 2020-03-24 09:07
Just a note for those following along, I was experiencing another bug due to my federation configuration: https://github.com/nextcloud/server/issues/20132

**Comment by menaceone** [comment] 2020-03-24 09:24
> Yep, sorry, 18.0.3 is an unexpected security update.
> 18.0.4 it is :)

Hey,
is there any (roughly) estimated release date for 18.0.4 or is it "done when it's done"?

**Comment by adsworth** [comment] 2020-03-24 09:26
> 
> Hey,
> is there any (roughly) estimated release date for 18.0.4 or is it "done when it's done"?

Apparently 23rd of April is the planned date.

https://github.com/nextcloud/server/milestone/115

**Comment by BotoX** [comment] 2020-03-24 14:44
First it's been 18.0.2, then 18.0.3 and now 18.0.4 which could take another month+
Can I just upgrade the photos plugin on my nextcloud install and skip yet another month of all my albums being down?

I really appreciate the work you guys put into this project, I've got a few smaller ones of my own and know how hard it can be to deal with lots of user inquiries in your free time.
But the way this has been handled so far is a really big turnoff for nextcloud.
At least present some kind of fix for affected people, since the code has seemingly already been written but not included in the release?
Thank you.

P.S. should this issue really be closed when it's not fixed in nextcloud yet?

**Comment by skjnldsv** [comment] 2020-03-24 14:47
> P.S. should this issue really be closed when it's not fixed in nextcloud yet?

fixed and released are two different things :)

**Comment by skjnldsv** [comment] 2020-03-24 14:51
> At least present some kind of fix for affected people, since the code has seemingly already been written but not included in the release?

Feel free to patch it yourself from the viewer/server code.
The pull requests have been linked in this issues and the associated ones.

> But the way this has been handled so far is a really big turnoff for nextcloud.

We don't aim for weird patches and quick releases unless those touches security. Stability is the most important thing. If you want to skip the beta and rc tests phases to have your own instance up and running, feel free to do so. But This is a project that aims to be serious and professional and we cannot afford to risk things for the sake of having users not wait 1 month for a fix.

**Comment by hroling** [comment] 2020-03-24 15:06
Is it possible to use the new app in NC 18.0.3? And, if yes, how?

**Comment by Leon5x** [comment] 2020-03-29 21:01
A workaround until NC 18.0.4 is released is described here: 
[https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/20](https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/20)
You can enable the old gallery app under NC 18. But this app does only work on public shares without a password when you use the sharing link like before (url.com/apps/gallery/s/awhdkawhd).
Btw, thanks for fixing everything for the next release properly!

**Comment by ricain** [comment] 2020-03-30 08:25
> Yep, sorry, 18.0.3 is an unexpected security update.
> 18.0.4 it is :)

Why do you need to wait for a server upgrade if you can publish an new release of just the app?
Whats the goal of having a separate app if development and release is bind to server release?
🤔 

Anyway thank for this great open source project 🥇

**Comment by skjnldsv** [comment] 2020-03-30 08:27
> Whats the goal of having a separate app if development and release is bind to server release?

This is not a separate app, this is a separate repository.
This app is shipped with server releases :)

**Comment by Chillstice** [comment] 2020-04-23 19:54
18.0.4 finally came out today and I was excited to update and check out if this works again. Turns out, not really.

The functionality appears to be returned - clicking an image from a gallery/ folder via shared link displays a lightbox - but the image never loads. It just indefinitely shows the loading animation.

I'm trying this with already existing shared-folders and I haven't tested extensively, but so far it doesn't appear to be working as intended.

**Comment by NOTNlCE** [comment] 2020-04-23 19:56
> The functionality appears to be returned - clicking an image from a gallery/ folder via shared link displays a lightbox - but the image never loads. It just indefinitely shows the loading animation.

I updated this morning and am NOT experiencing the above issue. Mine seems to work as intended, but I shared my albums fresh this morning.

**Comment by mwllgr** [comment] 2020-04-23 19:58
It works for me too. And I shared the album around three months ago.

**Comment by Chillstice** [comment] 2020-04-23 20:00
I just checked the console in a fresh chrome browser and I'm getting what appears to be a permission issue?
https://s.chillstice.com/ajHke

**Comment by szaimen** [comment] 2020-04-23 20:01
> 18.0.4 finally came out today and I was excited to update and check out if this works again. Turns out, not really.
> 
> The functionality appears to be returned - clicking an image from a gallery/ folder via shared link displays a lightbox - but the image never loads. It just indefinitely shows the loading animation.
> 
> I'm trying this with already existing shared-folders and I haven't tested extensively, but so far it doesn't appear to be working as intended.

I have the same problem. But it also doesn't work with new shares.

I am using external storage. Could that be the problem here?

**Comment by szaimen** [comment] 2020-04-23 20:05
@NOTNlCE @mwllgr @Chillstice 
Are you using external storage? That might be the problem here.

**Comment by NOTNlCE** [comment] 2020-04-23 20:05
I AM using External storage.

**Comment by mwllgr** [comment] 2020-04-23 20:06
@szaimen Nope, my files are stored locally and not encrypted on the server.

**Comment by benoitmasson** [comment] 2020-04-23 20:19
Same for me with Firefox 75, in private browsing mode. I get a 401 error when trying to view an image (album listing and miniatures show correctly).

Exact error message in the HTTP response is:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message/>
</d:error>
```

**Comment by Chillstice** [comment] 2020-04-23 20:20
I'm also seeing what might be a related error in the nextcloud log viewer:
`

Warning | l10n | Failed to load /var/www/cloud/public_html/apps/drop_account/l10n/en.json - json error code: 4


`

**Comment by neufeind** [comment] 2020-04-23 23:12
Same error here: NotAuthenticated ... 401
18.0.4 with local storage (but data-dir outside of the webroot), public link to a newly shared folder.
The folder opens, showing a list of files. But clicking on one gives that 401-error.

**Comment by ForgetMeOrNot** [comment] 2020-04-23 23:39
See this bug:
[#20132](https://github.com/nextcloud/server/issues/20132) 

You need to enable "Allow users on this server to send shares to other servers" in federation sharing

**Comment by Chillstice** [comment] 2020-04-24 00:03
> 
> 
> See this bug:
> [#20132](https://github.com/nextcloud/server/issues/20132)
> 
> You need to enable "Allow users on this server to send shares to other servers" in federation sharing, to get rid of 401 or infinite loading

omg that fixed it for me, but why??!?

**Comment by Atlantis1979** [comment] 2020-07-12 11:53
> 
> 
> See this bug:
> [#20132](https://github.com/nextcloud/server/issues/20132)
> 
> You need to enable "Allow users on this server to send shares to other servers" in federation sharing, to get rid of 401 or infinite loading

After hours of research, this is the only thing that worked for me too. Thank you for saving me from madness.
