### ISSUE TITLE
High load on Browser with big picture collection (>2000 pictures)

### ISSUE THREAD

**Issue by jonascant** [nextcloud/photos#40] opened 2019-12-15 21:49 UTC
It seams this app loads a placeholder for every picture in the user folder in the browser. 
My Browser warns me, that this website is slowing my PC down. Maybe the thumbnails shouldn't all be generated at once, but rather in blocks of say 100 pictures?

Server: Debian Buster
Nextcloud Verson: 18.0.0 Beta2
Php 7.3
Maria DB 10

Client: Manjaro Linux
Webbrowser: Firefox 71
16 GB Ram
8 Core Ryzen System

**Comment by skjnldsv** [comment] 2019-12-16 08:00
duplicate of #7 :)

**Closed by skjnldsv** 2019-12-16 08:00 UTC
