### ISSUE TITLE
Custom path for photos directory

### ISSUE THREAD

**Issue by marcrleonard** [nextcloud/photos#228] opened 2020-03-07 17:22 UTC
It would be great to allow a custom path for the photos directory. I have all my photos in a folder on my external hard drive, so it would be nice to point the photos app to that External Storage path. 

... Apologies if this has already been suggested - but I couldn't find any reference to it.

**Comment by skjnldsv** [comment] 2020-03-09 09:21
Duplicate of #141

**Closed by skjnldsv** 2020-03-09 09:21 UTC
Labels: 0. Needs triage, enhancement
