### ISSUE TITLE
Hidden files and folders are displayed

### ISSUE THREAD

**Issue by RobMahn** [nextcloud/photos#1156] opened 2022-08-13 15:13 UTC
**Describe the bug**
Photos displays hidden files.

**To Reproduce**
1. Add a hidden photo file.  e.g. Add a "." to the beginning of the file name.
2. Go to the Photos view.
3. The file is still displayed.
4. There is no option to view / not view hidden files.

My condition is that I'm using Resilio Sync to have a two way sync from my Android phone.  This syncs the phones ".trashed-* and .pending-* files.

**Expected behavior**
Hidden files should not be displayed, unless an option is added to display them.

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome

**Comment by skjnldsv** [comment] 2022-08-14 08:06
Hi, which version of Nextcloud? :)

**Comment by RobMahn** [comment] 2022-08-14 13:21
Nextcloud 24.0.4
... sorry for the omission.

**Comment by joshtrichards** [comment] 2023-07-16 17:03
Duplicate of #1061.

**Closed** 2023-10-07 01:49 UTC
Labels: bug, 0. Needs triage, needs info
