### ISSUE TITLE
Not all photo folders showing as albums

### ISSUE THREAD

**Issue by TheNetStriker** [nextcloud/photos#187] opened 2020-02-11 16:37 UTC
I've just switched to Nextcloud 18 and the new Photos app. In my account are a lot of folders with photos, but only 32 of them are listed as albums in the Photos app. But if I manually enter the name of one of the missing folders in the url I can browse the missing album.

Is this a known problem or how can I solve this problem?

**Comment by skjnldsv** [comment] 2020-02-24 09:24
Hey! Thanks for your report :)
That' is odd, could you share the content of one of your missing album?

**Comment by TheNetStriker** [comment] 2020-02-24 10:36
Sadly I cannot share the content, but I guess I know what causes this confusion. I have several folders with subfolders containing pictures. Some of the main Folders also contain pictures, but some do not. Here is a simple example:

MainFolder1
    SubFolder1
        Picture1
MainFolder2
    SubFolder2
        Picture2
    Picture3

In this case the SubFolder1 and MainFolder2 would show up as albums on the top level, but SubFolder2 is not shown on top level but as a sub album of the MainFolder2.

Is there maybe a way to always show the whole folder structure like it was in the old picture app even if the main folders do not contain a picture directly?

**Comment by skjnldsv** [comment] 2020-02-24 11:49
> Is there maybe a way to always show the whole folder structure like it was in the old picture app even if the main folders do not contain a picture directly?

AH, so this would be a duplicate of #142 ?(https://github.com/nextcloud/photos/issues/142#issuecomment-579275779)

**Comment by TheNetStriker** [comment] 2020-02-24 21:29
@skjnldsv Yes this seems to describe exactly what I'm experiencing, but I guess there will be no change to this as far as I saw in the other issue?

**Comment by skjnldsv** [comment] 2020-02-25 08:07
No idea yet :)
Let's continue on the other issue

**Closed by skjnldsv** 2020-02-25 08:07 UTC
Labels: 0. Needs triage, bug, needs info
