### ISSUE TITLE
No previews on stable27 branch

### ISSUE THREAD

**Issue by blizzz** [nextcloud/photos#1926] opened 2023-07-07 13:38 UTC
**Describe the bug**

On sections like "All media", "Photos" or "Tags → $Tag" (did not check others, I guess it is the same - the tag overview has previews) no previews are shown on the grid. Instead there is a grey rectangle. Clicking on that shows the picture however. 

![Screenshot_20230707_153325](https://github.com/nextcloud/photos/assets/2184312/404235d2-88b3-4829-82f8-d87521ca3e35)

**To Reproduce**
1. Go to Photos app
2. Click on "Photos"

**Expected behavior**
Previews of the pictures are shown

**Desktop (please complete the following information):**
 - OS: Linux (I use Arch btw)
 - Browser: firefox
 - Version: 115

**Browser log**

Repeatedly:

```
DOMException: The operation is insecure.
    l https://nc.zara/stable27/apps-repos/photos/js/photos-src_mixins_AbortControllerMixin_js-src_mixins_FilesSelectionMixin_js-src_components_File_vue--80ca54.js?v=c08cffe64c0343408669:2
    mounted https://nc.zara/stable27/apps-repos/photos/js/photos-src_mixins_AbortControllerMixin_js-src_mixins_FilesSelectionMixin_js-src_components_File_vue--80ca54.js?v=c08cffe64c0343408669:2
    Mt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    cn https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    insert https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    C https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    $a https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    _update https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    r https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    get https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    run https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    yn https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    zt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    Zt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    promise callback*jt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    zt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    vn https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    update https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    notify https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    20144 https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    VueJS 2
    Mt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    n https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    Mt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    $emit https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    needContent https://nc.zara/stable27/apps-repos/photos/js/photos-src_mixins_AbortControllerMixin_js-src_mixins_FilesSelectionMixin_js-src_components_File_vue--80ca54.js?v=c08cffe64c0343408669:2
    Mt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    n https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    Mt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    $emit https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    rows https://nc.zara/stable27/apps-repos/photos/js/photos-src_mixins_AbortControllerMixin_js-src_mixins_FilesSelectionMixin_js-src_components_File_vue--80ca54.js?v=c08cffe64c0343408669:2
    Mt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    run https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    yn https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    zt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    Zt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    promise callback*jt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    zt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    vn https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    update https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    notify https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    set https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    init https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    init https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    updateRoute https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    transitionTo https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    confirmTransition https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    r https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    r https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    Mt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    confirmTransition https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    r https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    r https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    m https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    Bt https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    m https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    r https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    r https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    r https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    m https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    beforeRouteLeave VueJS
    Ut https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    m https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    r https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
    r https://nc.zara/stable27/apps-repos/photos/js/photos-main.js?v=dcbe9e84-8:2
photos-main.js:2:2861510

```

**Comment by blizzz** [comment] 2023-07-07 13:39
P.S.: I did not check master, I was on stable27 and checked whether my backport was not the cause.

**Comment by artonge** [comment] 2023-07-07 14:59
Duplicate of https://github.com/nextcloud/photos/issues/1885

**Closed by artonge** 2023-07-07 14:59 UTC
Labels: bug, 0. Needs triage
