### ISSUE TITLE
Set tags easily

### ISSUE THREAD

**Issue by Schmidtjanroman** [nextcloud/photos#827] opened 2021-07-03 04:19 UTC
**Is your feature request related to a problem? Please describe.**
Sorting by tags is possible in the photos app, to set tags is not even a hidden function or feature nor available feature.
To set a tag, its only possible to find the photo in via the file browser, open the sidelist and klick on the "...". Very complicated, not handy, not user friendly.

**Describe the solution you'd like**
Set tags should be an ease in the photos app, maybe directly within the picture preview, not online in the sidelist.

**Describe alternatives you've considered**
Can't provide alternatives

**Additional context**
I've made some screenshots, but I'm unable to upload them to git here.

**Comment by mathys-lab** [comment] 2021-07-30 12:59
I second this. This is a critical factor in my opinion. Tags allow me to organize photos into certain categories without having to duplicate the file or store it in a specific location.

It also seems as though it isn't very easy to add photos to favorites from the photos app, is that true or is it just me? In my experience, the only way I can get them listed in the favorites tab is if I find the photo in Files and then favorite it.

**Comment by Spartachetto** [comment] 2021-08-03 22:22
This is the _photos_ version of https://github.com/nextcloud/gallery/issues/153 opened by me some time ago... :blush:

**Comment by tflidd** [comment] 2022-05-07 09:37
Looks like a duplicate of https://github.com/nextcloud/photos/issues/551

**Closed** 2022-06-10 16:14 UTC
Labels: enhancement, 0. Needs triage

**Comment by overholted** [comment] 2023-05-17 13:29
Any progress on this yet? Being able to easily manage tags for photos is the biggest feature I need in Nextcloud. If this was available I'd be able to use it for several clients' projects. Frankly, I'm surprised this wasn't thought of in the first implementation of Photos.

**Comment by rolszewo** [comment] 2023-06-01 05:15
really missing this feature.
couldn't believe, it is not there.
current Procedure is:
- view photos
- remember which one or two i want to tag
- got to files
- search and find those photos again
- set tags
- go back to photos
- continue

Isn't this a bad workflow? To be done in endless rounds.
