### ISSUE TITLE
Remove button missing

### ISSUE THREAD

**Issue by Rychu-Pawel** [nextcloud/photos#222] opened 2020-03-01 20:24 UTC
This is a feature request for a remove button that the old gallery app had that could be used to remove photos. 
To me and to the other user on my server it was a very important thing. 
Without this button it is necessary to close the app and find the photo you decided to remove on the list and then remove it. Not much user friendly.

**Comment by skjnldsv** [comment] 2020-03-02 07:13
Do you mean in the photo slideshow view or in the photos grid view?

**Comment by Rychu-Pawel** [comment] 2020-03-02 08:52
In the single photo preview (I guess this is the slideshow view), not the grid.

**Comment by skjnldsv** [comment] 2020-03-02 11:25
Then duplicate of https://github.com/nextcloud/viewer/issues/147 :)

Thanks for reporting! :hugs:

**Closed by skjnldsv** 2020-03-02 11:25 UTC
Labels: 0. Needs triage, enhancement, needs info, regression
