### ISSUE TITLE
Add photos to albums from Folders view

### ISSUE THREAD

**Issue by darguez** [nextcloud/photos#1426] opened 2022-10-26 11:37 UTC
It would be great to allow adding files to an album from Folders view, because it is esaier to find the photos you want to include from your organized folders.

**Comment by pspitzli** [comment] 2022-10-29 08:51
This should also include the folders listed in the Photos-App itself.

**Comment by artonge** [comment] 2022-11-08 13:37
Duplicate of https://github.com/nextcloud/photos/issues/1365

**Closed by artonge** 2022-11-08 13:37 UTC
Labels: enhancement, 1. to develop
