### ISSUE TITLE
Download button in preview mode

### ISSUE THREAD

**Issue by antonkarliner** [nextcloud/photos#505] opened 2020-10-20 19:44 UTC
**Is your feature request related to a problem? Please describe.**
There's no button for downloading pictures when they are browsed in a preview mode. Therefore if you like the picture and want to download it, you have to close the preview, remember the filename, scroll through files to find the needed one, then press three dots and then press "download".

**Describe the solution you'd like**
I would be great to have a download button in the preview mode. A user could download the picture without the having to close preview and find corresponding file.

**Additional context**
Usecase example: user one shares a big selection of pictures with user two. User two browses through them in preview mode and instantly downloads the picture he/she likes with one click.

Quick sketch:
![sketch](https://user-images.githubusercontent.com/19594480/96636262-b9fcc400-1325-11eb-90ab-416731d78c96.jpg)

**Comment by skjnldsv** [comment] 2020-10-20 20:12
Duplicate of https://github.com/nextcloud/viewer/issues/88

**Closed** 2020-10-20 20:13 UTC
Labels: duplicate, enhancement
