### ISSUE TITLE
Photo App 2.0 Face Recognition

### ISSUE THREAD

**Issue by andypmuc** [nextcloud/photos#1469] opened 2022-11-10 17:22 UTC
I have used the face recognition to crawl to my entire photo database of 400 GB. In the beginning it worked well, but after a while it didn't any more. I checked the mariadb log and in a few seconds 20k - 40k Select statements were made in the database. I assume the programming needs to be approved to reduce this number. I also have problems that the images are not loaded any more and the browser hangs up, I assume it has something to do with the database requests.

**To Reproduce**
1. Open Nextcloud
2. Open Photo App
3. Click on faces or persons

**Expected behavior**
No performance issues ;-).

**Screenshots**
See console.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**
 - n/a

**Browser log**

![image](https://user-images.githubusercontent.com/6280331/201163754-557cb79c-072c-46b9-99e1-01f232ff9dba.png)

**Comment by corsac-s** [comment] 2022-11-14 10:50
Does this mean the default photo app now includes face recognition? How can we enable that?

**Comment by markuman** [comment] 2022-11-17 06:17
> Does this mean the default photo app now includes face recognition? How can we enable that?

imo, you must download and enabled it by yourself - and follow the instructions of recognize in the admin menu.

**Comment by andypmuc** [comment] 2022-11-20 20:52
I think this issue is more something for the recognize app. https://github.com/nextcloud/recognize/issues/509

**Comment by marcelklehr** [comment] 2022-11-21 08:04
This is a duplicate of #1411

**Closed by marcelklehr** 2022-11-21 08:04 UTC
Labels: bug, 0. Needs triage
