### ISSUE TITLE
index.php/apps/photos/api/v1/preview/5099927?x=512&y=512" resulted in a network error response: the promise was rejected.

### ISSUE THREAD

**Issue by gmeks** [nextcloud/photos#1411] opened 2022-10-20 18:12 UTC
**Describe the bug**
Opening Photos people kills the browser, it will use 100% CPU. 

**To Reproduce**
1. Have lots of photos, and reconigesed people( We 200gb++)
2. Photos
3. People

If it mathers, i have recognize 3.10

**Expected behavior**
The brower should not attemt to download all preview at once, this is kills the browser and likely server side to.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://imgur.com/a/AWnpsjt)

**Desktop (please complete the following information):**
 - Browser firefox and  edge

Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
The FetchEvent for "https://cloud.thexsoft.com/index.php/apps/photos/api/v1/preview/5123010?x=512&y=512" resulted in a network error response: the promise was rejected.
The FetchEvent for "https://cloud.thexsoft.com/index.php/apps/photos/api/v1/preview/5099623?x=512&y=512" resulted in a network error response: the promise was rejected.
The FetchEvent for "https://cloud.thexsoft.com/index.php/apps/photos/api/v1/preview/5099675?x=512&y=512" resulted in a network error response: the promise was rejected.

Please note the page that you use to modal that you use to merge faces have simular performance issues.

**Comment by skjnldsv** [comment] 2022-10-21 07:13
I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by skjnldsv** [comment] 2022-10-21 08:38
Hi, please open a different ticket for this :)
I'll wait for your image preview failure network log screenshots :+1:

**Comment by skjnldsv** [comment] 2022-10-21 08:44
Why closing? 

> Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
> The FetchEvent for "https://cloud.thexsoft.com/index.php/apps/photos/api/v1/preview/5123010?x=512&y=512" resulted in a network error response: the promise was rejected.

Is this fixed?

**Comment by gmeks** [comment] 2022-10-21 12:29
No its not fixed, but i seem to lack the written skill to persuade you that opening 6500 requests in 1 go is a bad idea. Getting attached to where it fails is likely not going to be productive.

Most of the time browser will become some slugish the user will close it.
Sometimes the browser fails to find enough RAM for the tab.
Some of the time the reverse proxy will timeout requets.
Sometimes the server will give up.

The photo app, when you click people. 
![bilde](https://user-images.githubusercontent.com/4104522/197194024-c5d06678-78dd-4108-acfe-77eb788e4da7.png)

![bilde](https://user-images.githubusercontent.com/4104522/197181479-edc78510-a561-47ad-b7a6-28f909df1e22.png)

6500 in this case is the number of faces that my instance has found untill now, i have a relativlity small instance of a 1tb.  Thats far from done with scanning over the images.

**Comment by artonge** [comment] 2022-10-21 13:12
@marcelklehr any idea of what could be the issue here ?

**Comment by marcelklehr** [comment] 2022-10-21 13:29
Off. The problem is likely that it's fetching so many faces. I never tested with so many faces :/ A fix would involve counting the number of face detections per person and passing that number to photos via DAV so the app can do some lazy loading.

**Comment by artonge** [comment] 2022-10-21 15:58
If I understand correctly, the peoples view loads the content of all the faces ? You can take a look how it is done for albums, we indeed pass the number of items in the DAV response:

https://github.com/nextcloud/photos/blob/fe37e5ae559133437329a73a9550e6a4088facf5/lib/Sabre/Album/PropFindPlugin.php#L129

**Comment by skjnldsv** [comment] 2022-10-22 06:25
> No its not fixed, but i seem to lack the written skill to persuade you that opening 6500 requests in 1 go is a bad idea. Getting attached to where it fails is likely not going to be productive.

Sorry, that was not my point at all.
Your initial post mentons an issue with web worker and previews
> The FetchEvent for "[cloud.thexsoft.com/index.php/apps/photos/api/v1/preview/5123010?x=512&y=512](https://cloud.thexsoft.com/index.php/apps/photos/api/v1/preview/5123010?x=512&y=512)" resulted in a network error response: the promise was rejected.
> The FetchEvent for "[cloud.thexsoft.com/index.php/apps/photos/api/v1/preview/5099623?x=512&y=512](https://cloud.thexsoft.com/index.php/apps/photos/api/v1/preview/5099623?x=512&y=512)" resulted in a network error response: the promise was rejected.
>  The FetchEvent for "[cloud.thexsoft.com/index.php/apps/photos/api/v1/preview/5099675?x=512&y=512](https://cloud.thexsoft.com/index.php/apps/photos/api/v1/preview/5099675?x=512&y=512)" resulted in a network error response: the promise was rejected.

This has nothing to do with People, and I wanted to investigate this.
If possible then, could you open another ticket for those errors? If they happen often too :)

Let's keep that issue about People then, I misunderstood that was the original point :+1:

**Comment by skjnldsv** [comment] 2022-10-22 06:27
> Off. The problem is likely that it's fetching so many faces. I never tested with so many faces :/ A fix would involve counting the number of face detections per person and passing that number to photos via DAV so the app can do some lazy loading. I'll have a look at this on monday.

Virtual scrolling! :+1: 
Or you can also try to not load the image before the face gets added into the view (with debounce or scrolling to the bottom will load them all)

**Comment by gmeks** [comment] 2022-10-24 11:13
> This has nothing to do with People, and I wanted to investigate this.

My understanding when this happend ( Be aware that my javascript skills, are very limited.). Its basicly a memory restriction that happen in firefox ( This was based on searching). Basicly there is a unkown limit of how many promises you can make, before the browser kills them.

So virtual scrolling type solution should fix this issue also. But i will offcourse retest when a new app version is out

**Closed** 2022-11-11 13:38 UTC
Labels: bug, 0. Needs triage, needs info

**Comment by gmeks** [comment] 2022-11-17 18:49
At the risk of being rude, but if a RC/Beta build could be published via the store i clould do some testing.
