### ISSUE TITLE
Remember the last opened view

### ISSUE THREAD

**Issue by Bodenseematze** [nextcloud/photos#349] opened 2020-06-04 13:57 UTC
I don't like the flattened view of the new photo app - I liked the behavior of the old gallery app, to only show the photos of the current directory and show the sub directory as folders with some generated thumbnails of the content on it.

--> please bring the possibility to have such a view (as option or as button to switch the view from "flatten" to "structured" or...) back!

**Comment by Spartachetto** [comment] 2020-06-05 10:11
Did you try to click on "Your Albums" on the left?

Isn't it what you're looking for?

**Comment by serenity182** [comment] 2020-06-19 09:02
I think you would like it that way

![Unbenannt](https://user-images.githubusercontent.com/489617/85115308-c1974980-b21b-11ea-97e3-c50818127aa3.png)

I would to extend this - my usecase:

1. My family is on a group event
2. everyone takes pictues
3. everyone uploads his photos automatially from the phone. 
4. A group/shared folder for the event is created
5. everyone can share their pictures to that folder by drag and drop from their own albums

**Comment by Bodenseematze** [comment] 2020-06-19 09:24
@Spartachetto : yes, I tried "Your albums" - it's a bit like what I want it.
But that should be the default view (or at least the default view should be configurable) and / or the last used view should be stored for the future.
And what's absolutely missing is the possibility to sort the pictures (by date, by name, ascending, descending, ...)

@serenity182 : yes, that is much more what I like - although it'll be hard to see all (sub)folders if you have a lot of them...

The very old Gallery+ was perfect for me - with that there were the "Gallery" button(s) in the top of each folder in the file app where you could switch the view between "file" and some gallery views.
Unfortunately that feature got lost in some Nextcloud version - I assume the API changed and it was no longer possible for apps to integrate in another app...

BTW, does the preview generator work with the new "Photos" app? Or does it ignore the generated preview images?

@serenity182 : I think your extension would be best in a "side by side" view where the "Photos" app can be opened twice - with different views and where you're able to drag and drop from one view to the other.
That's a really good idea - but should be written down in detail in another issue/suggestion... ;-)

**Comment by skjnldsv** [comment] 2020-07-14 07:57
> BTW, does the preview generator work with the new "Photos" app? Or does it ignore the generated preview images?

We're using Nextcloud's default preview generator like it's supposed to.


> But that should be the default view (or at least the default view should be configurable) and / or the last used view should be stored for the future.

No for the default view. @jancborchardt do you wish to have the last view remembered?



> And what's absolutely missing is the possibility to sort the pictures (by date, by name, ascending, descending, ...)

Not related to this issue, there is already dedicated thread for this :wink: 

> yes, I tried "Your albums" - it's a bit like what I want it.

We use the exact same mechanism as the old gallery iirc :)

Have a nice day!
Cheers

**Comment by skjnldsv** [comment] 2020-07-14 08:00
Ah, duplicate of https://github.com/nextcloud/photos/issues/271

**Closed by skjnldsv** 2020-07-14 08:00 UTC
Labels: 0. Needs triage, enhancement, needs info

**Comment by Bodenseematze** [comment] 2020-07-21 09:08
really "nice" reaction: ignore most of the criticism points, comining it to one point, change the title of the issue and then close it because it's a duplicate...
...make this to all of your issues and you're done - then everything is fine with the photo app and it can stay as it is...!
:-(

**Comment by skjnldsv** [comment] 2020-07-21 09:33
Hey!
I thought I answered most of your points, which one do you wish to get clarification?
