### ISSUE TITLE
Sorting pictures by date, date of execution, name and size.

### ISSUE THREAD

**Issue by kbanaszak** [nextcloud/photos#497] opened 2020-10-17 22:07 UTC
Hello I uploaded a thousend of pictures from my phone but they sort without order. 

There should be the option to sort them by date, date of execution, name or size in each folder.
They should also be sorted by date of execution by default then the order would be correct.

**Comment by Mikescops** [comment] 2020-10-18 09:15
Hello, this is duplicate of #397

**Closed by Mikescops** 2020-10-18 09:15 UTC
Labels: 0. Needs triage, duplicate, enhancement
