### ISSUE TITLE
Diaporama timing to fast, could it be adjustable ?

### ISSUE THREAD

**Issue by feydreva** [nextcloud/photos#428] opened 2020-08-24 13:39 UTC
**Is your feature request related to a problem? Please describe.**
During diaporama, it changes pictures every 3 seconds

**Describe the solution you'd like**
We should be able to choose the timimg during which the photo is displayed.. 3s is too fast

**Describe alternatives you've considered**
A drop down, with 3s, 5s, 10 for exemple ?

**Comment by skjnldsv** [comment] 2020-08-24 13:53
Dupe of https://github.com/nextcloud/viewer/issues/447

**Closed by skjnldsv** 2020-08-24 13:53 UTC
Labels: 0. Needs triage, enhancement
