### ISSUE TITLE
Gallery-view for shared photos-folders not available

### ISSUE THREAD

**Issue by neufeind** [nextcloud/photos#182] opened 2020-02-07 14:43 UTC
https://github.com/nextcloud/server/issues/19019
The above mentioned issue says that in Nextcloud pre-18 a gallery-view, like it is available for a folder after login, was also available publically for a share. It looks like that was a feature of the gallery-app but the new photos-app does not yet support it?

**Comment by skjnldsv** [comment] 2020-02-07 15:18
duplicate of #128

**Closed by skjnldsv** 2020-02-07 15:18 UTC
