### ISSUE TITLE
Add timescale for navigation

### ISSUE THREAD

**Issue by Ilia1** [nextcloud/photos#848] opened 2021-08-10 11:20 UTC
When there are many photos taken at different times and not sorted into folders, it is difficult to find old photos.

The decision to make the timeline as in Yandex.Disk or Plex.
![timescale-yd](https://user-images.githubusercontent.com/16576224/128857898-243add0c-7d8b-450e-9f55-0ccffecac87d.png)

**Comment by skjnldsv** [comment] 2021-08-10 11:25
Hey! Duplicate of https://github.com/nextcloud/photos/issues/426

**Closed by skjnldsv** 2021-08-10 11:25 UTC
Labels: enhancement, 0. Needs triage
