### ISSUE TITLE
Change the order of the photos

### ISSUE THREAD

**Issue by grenzverkehr** [nextcloud/photos#237] opened 2020-03-13 14:08 UTC
There should be the possibility to decide in which order the photos should be displayed: file name (forward, backward) and taken date (forward, backward).
In the Gallery-App it was possible to change the order of the photos. You could choose between file name (forward, backward) and modification date (forward, backward). Default was filename (forward). It was also possible to change the order of the photos in public gallery links. Now the photos are displayed according to the modification date (backwards): https://github.com/nextcloud/photos/issues/87

**Comment by skjnldsv** [comment] 2020-03-18 15:28
cc @jancborchardt should we?

**Comment by jancborchardt** [comment] 2020-03-20 22:15
It should just work. All usual photos apps are sorted by date and nothing else, and that’s the proper way to do it.

Filename sort makes 0 sense as when your IMG_0001 naming rolls over or you use 2 different devices it messes up.

This is also a duplicate of https://github.com/nextcloud/photos/issues/87, closing hence.

**Closed by jancborchardt** 2020-03-20 22:15 UTC
Labels: 0. Needs triage, discussion, enhancement, needs info
