### ISSUE TITLE
Getting 'ghost' duplicates after closing viewer

### ISSUE THREAD

**Issue by githubertus** [nextcloud/photos#266] opened 2020-03-29 16:58 UTC
**Describe the bug**
Running on a simple directory structure with topfolder 'Photos' and Subfolder1 - each of those containing just one picture, I'm getting duplicates of both Pic1 and Pic2 after viewing Pic2 and closing the viewer afterwards. Viewing Pic1 gives no duplicates.

**To Reproduce**
1. open apps/photos
2. click the right pic (console: Opening viewer for file  /Photos/Subfolder1/Pic2.jpg)
3. close viewer
4. Pic1 and Pic2 appear twice

**Expected behavior**
getting the same view as before

**Screenshots**
![photos](https://user-images.githubusercontent.com/9904364/77854553-4bbaad80-71eb-11ea-90c9-cc97499298fc.jpg)
![subfolder1](https://user-images.githubusercontent.com/9904364/77854584-5f661400-71eb-11ea-8229-0b0390514810.jpg)
![deine-fotos](https://user-images.githubusercontent.com/9904364/77854600-74db3e00-71eb-11ea-9b73-79e522d7270b.jpg)
![duplicates](https://user-images.githubusercontent.com/9904364/77854608-7b69b580-71eb-11ea-8893-6a5a8d6bd5c4.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, firefox
 - Version latest

Nextcloud 18.0.3 + Photos 1.0.0

**Comment by githubertus** [comment] 2020-03-29 21:27
Let me just add what I saw in my networking console:
While clicking on Pic1 gives only 1 xhr request like
`remote.php/dav/files/Githubertus/Photos/Pic1.jpg`
clicking on Pic2 not only gives
`remote.php/dav/files/Githubertus/Photos/Subfolder1/Pic2.jpg`
but an additional
`remote.php/dav/`
which in fact returns the previews of both files again

Creating a new Subfolder2 with Pic3.jpg in Subfolder1
removes the effect from Pic2, but this time it's getting triggered when clicking Pic3

Hence, it looks like it's always the first picture in the last subfolder which is triggering the bug.

**Comment by skjnldsv** [comment] 2020-10-12 18:29
yes, and duplicate of #404

**Comment by Mikescops** [comment] 2020-10-12 20:58
Keep this one open until the grid is everywhere.

**Comment by Mikescops** [comment] 2020-10-15 11:28
Fixed by #480 ! :tada:

**Closed by Mikescops** 2020-10-15 11:28 UTC
Labels: 0. Needs triage, bug
