### ISSUE TITLE
All media has issues to load all photos

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/photos#2143] opened 2023-11-21 13:09 UTC
see below
![Screenshot 2023-11-21 094330](https://github.com/nextcloud/photos/assets/1315170/5b680823-c581-41f7-b683-a3af1905e321)

latest master/28beta4+

**Comment by artonge** [comment] 2024-02-14 11:49
Closing. Feel free to reopen with reproduction steps.

**Comment by MrRinkana** [comment] 2024-02-27 21:24
**I can reproduce this issue consequently on 28.0.2 (photos 2.4.0).** 


1. Have a larger amount of pictures spread in subfolders (not sure if necessary)
2. Previews already generated by imaginary (for all images)
3. Open the "all media" section in photos
4. Scroll quickly (does not have to be that fast, just faster than about 1 image row/sec, at least in my case)

**Observed**: 

Some photos don't load, see images. Scrolling past them a bit (I suspect to a point they would be unloaded by browser) and then back they likely will have loaded, but just waiting does not make them appear. Sometimes this manifests in that the thumbnail stays as the 64px version rather than "upgrading" to 512x512, instead of not appearing at all. The amount of missing or low res thumbnails increases with scroll speed, in general (to a point).

<details>
<summary>Some images showcasing the issue (contains all observed outcomes; missing thumbnail both with filename and not, previews stuck at 64px - and fully loaded).</summary>

![Screenshot_20240226_195402](https://github.com/nextcloud/photos/assets/39345772/9ac9825e-1e0e-4c5f-a031-ede4840a2f82)
![Screenshot_20240226_202544](https://github.com/nextcloud/photos/assets/39345772/46c25515-1911-4ee0-9356-d6cc97fb1037)

</details>

Clicking on them does bring up the "full scale" preview.

I looked trough the network log to debug it a little and it seems the **resource is not requested at all**:
- I looked trough the status 200 requests, the missing image is not there.
- Neither amongst 404 requests (I compared the ID requested in the 404 request to the ID of the missing thumbnail appearing after I loaded it by scrolling as described
- I was playing around with my php-fpm configuration thinking it maybe could be something with it, during which i managed to get some 503 requests, but resending them (and getting 200) did not return the missing thumbnails.

In essence, none of 200, 404 or 503 requests contained the missing thumbnail, indicating its not even requested. Problem does not appear of one scrolls very slowly.

I found no combination of reverse proxy, apache (event, fcgi) or php-fpm configurations that would remove the issue, but Im not an expert in reverse prox - la(m)p stack. The setup used by the aio is probably also troubled, but I use a different reverse proxy. Hence I suspect the problem lies in the photos app.

Tested on both Firefox and edge (both on linux).

No logs appear in neither php errorlog or slowlog, apache errorlog, or nextcloud logs (level warn).

Let me know if you want configuration details, or me to test something.

**Comment by MrRinkana** [comment] 2024-03-06 14:24
I did some more testing:

I can not reproduce the issue on a test-instance I spun up using a [turnkey nextcloud lxc container](https://www.turnkeylinux.org/nextcloud), and the difference there is that it does not seem to use php-fpm. 

That made me suspect that maybe php-fpm is the culprit after all, so I played around some more with my main instance, and switching php-fpm to `pm = static` **got rid of the issue**.

I'll see if I can spin up the official docker image to see if the issue exists there, but since it uses.

I'm not sure if this is some interaction specific to nextcloud:php-fpm or if its unrelated to nextcloud (fully a php8.1 issue)

**Comment by MrRinkana** [comment] 2024-03-31 13:51
I don't know what changed (server was left untouched except for NC update) but I can no longer reproduce this on NC 28.0.4. I believe this can be closed. Sorry for the noise!

**Closed** 2024-04-17 15:18 UTC
Labels: bug, 1. to develop, regression

**Comment by github-k8n** [comment] 2024-04-29 13:08
Same issue here, nextcloud 29.0.0 , php 8.3 , on gentoo

Scrolling through images, seems some are not loaded at all. (don't see any rejected or otherwise not working requests,..) When scrolling back up, some of the previously shown images are gone as well...  whole things feels pretty random.
Looking at the folder in file viewer doesn't exhibit any of those issues regarding the previews
