### ISSUE TITLE
Err 404 when doing a preview of a video via menu "Folders" in Photo App

### ISSUE THREAD

**Issue by GretaD** [nextcloud/photos#1730] opened 2023-04-06 09:32 UTC
**Describe the bug**

**To Reproduce**

1. Open web app
2. Go to photo app
3. Go to "Folders" menu
4. Preview a video

**Expected behavior**
I can play the video

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Browser log**
```
Error when getting the preview + Err 404 in the console
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by artonge** [comment] 2023-05-10 09:55
Can't reproduce.
Might have been fixed by https://github.com/nextcloud/photos/pull/1648

**Closed by artonge** 2023-05-10 09:55 UTC
Labels: bug, 0. Needs triage

**Comment by artonge** [comment] 2023-05-10 10:08
Could reproduce in the end. Indeed fixed by #1648
