### ISSUE TITLE
Be able to download the original picture

### ISSUE THREAD

**Issue by tillwf** [nextcloud/photos#198] opened 2020-02-20 12:33 UTC
Once you clicked on a picture, add the possibility to download the original picture using an icon next to these:

![image](https://user-images.githubusercontent.com/7115035/74934026-9162aa00-53e5-11ea-8663-46fd40cc0a92.png)

**Comment by skjnldsv** [comment] 2020-02-21 08:26
Duplicate of https://github.com/nextcloud/viewer/issues/88

**Closed by skjnldsv** 2020-02-21 08:26 UTC

**Comment by tillwf** [comment] 2020-02-21 12:08
It is strange. As far as I remember it was still there for me in the version 17. It disappeared with the upgrade to NC18. But I guess it is not a `photos` issue.

**Comment by skjnldsv** [comment] 2020-02-21 20:47
Hey :)
A bit clarification, the slideshow/viewer is another dedicated app named `viewer`, photos is the new gallery but outsource the display of images to this viewer app that was introduced in nc 16 ;)

So it was still there in gallery (which was not using viewer), but since this is now photos, this is missing from viewer :+1:
