### ISSUE TITLE
Button to rotate images

### ISSUE THREAD

**Issue by Derkades** [nextcloud/photos#452] opened 2020-09-12 12:16 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes when looking through pictures in the photos app I see one with a wrong orientation. I have to look up the file name, navigate to it with the file manager, download it, open it in a photo editor, rotate it, save it, upload it.

**Describe the solution you'd like**
A button in the top bar of the image viewer that rotates the image 90 degrees. It can be clicked multiple times for 180 or 270 degrees rotation.

**Describe alternatives you've considered**

**Additional context**
A button here:
![image](https://user-images.githubusercontent.com/15892014/92995290-864aa500-f502-11ea-8ff9-48fcfe2b601d.png)

**Comment by skjnldsv** [comment] 2020-09-12 19:29
duplicate of https://github.com/nextcloud/viewer/issues/65

**Closed by skjnldsv** 2020-09-12 19:29 UTC
Labels: 0. Needs triage, enhancement
