### ISSUE TITLE
People view does not open photo

### ISSUE THREAD

**Issue by FadeFx** [nextcloud/photos#1614] opened 2023-01-26 19:11 UTC
**Describe the bug**
Ehen in People section i can open the folder of a person, but clicking a preview opens the image viewer, i see the arrows and the "start slideshow" button and the spinner which will never stop spinning and it does not show the image. It does open any of these pics from any other section.

**To Reproduce**
Open Photos
Open Peoples from sidebar
Click on a persons image
Klick on any pic there
No image in viewer

**Expected behavior**
See Image  in full size

The Dev console output from Chrome will be delivered later, i have seen this issue on mobile phone as well as on desktop.

**Comment by FadeFx** [comment] 2023-01-26 19:17
Chrome console output

xhr.js:220          PROPFIND https://my.domain.tld/remote.php/dav/files/USERNAME/files/USERNAME/Sync_Handy/Downloads/Fotos/Sebastian%20Schallenberg.png 404
(anonymous) @ xhr.js:220
e.exports @ xhr.js:16
e.exports @ dispatchRequest.js:56
p.request @ Axios.js:109
(anonymous) @ bind.js:9
(anonymous) @ functions.js:21
e.execute @ patcher.js:100
e.patchInline @ patcher.js:199
u @ request.js:13
t.request @ request.js:56
(anonymous) @ stat.js:62
(anonymous) @ stat.js:33
(anonymous) @ stat.js:14
(anonymous) @ stat.js:8
r @ stat.js:4
t.getStat @ stat.js:47
stat @ factory.js:80
(anonymous) @ FileInfo.js:33
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
cg @ DavClient.js:38
a @ DavClient.js:38
(anonymous) @ DavClient.js:38
(anonymous) @ DavClient.js:38
dg @ FileInfo.js:32
(anonymous) @ CancelableRequest.js:41
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Qm @ canDownload.js:26
a @ CancelableRequest.js:40
(anonymous) @ CancelableRequest.js:40
(anonymous) @ CancelableRequest.js:40
(anonymous) @ CancelableRequest.js:40
(anonymous) @ Viewer.vue:503
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Ig @ Pencil.vue?12b8:19
a @ Pencil.vue?12b8:19
(anonymous) @ Pencil.vue?12b8:19
(anonymous) @ Pencil.vue?12b8:19
openFile @ Viewer.vue:471
file @ Viewer.vue:355
Pt @ vue.runtime.esm.js:3017
e.run @ vue.runtime.esm.js:3534
yn @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Mt @ vue.runtime.esm.js:3065
Promise.then (async)
jt @ vue.runtime.esm.js:3090
Ht @ vue.runtime.esm.js:3155
bn @ vue.runtime.esm.js:4207
e.update @ vue.runtime.esm.js:3513
e.notify @ vue.runtime.esm.js:720
set @ vue.runtime.esm.js:963
value @ Viewer.js:246
openViewer @ FaceContent.vue:288
Rt @ vue.runtime.esm.js:3015
n @ vue.runtime.esm.js:1813
Rt @ vue.runtime.esm.js:3015
e.$emit @ vue.runtime.esm.js:3714
emitClick @ File.vue:185
click @ File.vue?vue&type=template&id=14205f7c&scoped=true&:1
Rt @ vue.runtime.esm.js:3015
n @ vue.runtime.esm.js:1813
Jr.i._wrapper @ vue.runtime.esm.js:7458
Viewer.vue:507 Could not open file /files/USERNAME/Sync_Handy/Downloads/Fotos/Sebastian Schallenberg.png Error: Invalid response: 404 
    at i (response.js:10:15)
    at t.handleResponseCode (response.js:21:19)
    at stat.js:65:36
    at stat.js:33:23
    at Object.next (stat.js:14:53)
    at a (stat.js:5:58)
(anonymous) @ Viewer.vue:507
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Ig @ Pencil.vue?12b8:19
s @ Pencil.vue?12b8:19
Promise.then (async)
Ig @ Pencil.vue?12b8:19
a @ Pencil.vue?12b8:19
(anonymous) @ Pencil.vue?12b8:19
(anonymous) @ Pencil.vue?12b8:19
openFile @ Viewer.vue:471
file @ Viewer.vue:355
Pt @ vue.runtime.esm.js:3017
e.run @ vue.runtime.esm.js:3534
yn @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Mt @ vue.runtime.esm.js:3065
Promise.then (async)
jt @ vue.runtime.esm.js:3090
Ht @ vue.runtime.esm.js:3155
bn @ vue.runtime.esm.js:4207
e.update @ vue.runtime.esm.js:3513
e.notify @ vue.runtime.esm.js:720
set @ vue.runtime.esm.js:963
value @ Viewer.js:246
openViewer @ FaceContent.vue:288
Rt @ vue.runtime.esm.js:3015
n @ vue.runtime.esm.js:1813
Rt @ vue.runtime.esm.js:3015
e.$emit @ vue.runtime.esm.js:3714
emitClick @ File.vue:185
click @ File.vue?vue&type=template&id=14205f7c&scoped=true&:1
Rt @ vue.runtime.esm.js:3015
n @ vue.runtime.esm.js:1813
Jr.i._wrapper @ vue.runtime.esm.js:7458
index.js:323 OC.requestToken changed ZWqP9Vbi22iCsxnAV6HgdbhcgDUE5cLL5gbApWYpo2I=:UxLCshupry7Gy1CoOMLZLd861VBPhIGJ1XWYwklIzDg=

i have checked the location of the images and it is actually correct, except the path containing the domain has /dav/files/USERNAME/files/USERNAME/ where one files/USERNAME/ part is too much

**Comment by shalak** [comment] 2023-02-02 01:56
Please use proper formatting when pasting logs and check for typos, when you're describing the issues - that way, we'll get more traction on getting devs to fix something :)

The `Viewer.vue` entry seems unrelated, it just shows a log. The actual path is properly URL-encoded.

But you've noticed the real problem, and I'm seeing the same issue - the 404 on PROPFIND call has duplicated `/files/USERNAME/` prefix in path: `remote.php/dav/files/USERNAME/files/USERNAME/DirectoryInMyMainFolder`

Seems like this should be a trivial fix 🤔

**Comment by zlatko0o** [comment] 2023-02-03 22:45
I am having the same issue. Once the faces are generated, I cannot open any photos from the selected "Face".

One of the things that I noticed is that the URL is wrong.

The working one is => /remote.php/dav/files/admin/Photos
The URL that the Face preview generates is => /remote.php/dav/files/admin/files/admin/Photos/ notice the double "files/admin"

**Comment by FadeFx** [comment] 2023-02-04 03:05
"Also when you click on the photo and move back/forward it seems to be working."

Thanx, ddint see that before...

**Comment by phil-lipp** [comment] 2023-02-27 09:32
duplicate of #1594

**Comment by marcelklehr** [comment] 2023-02-27 11:19
This should be fixed in v25.0.4

**Closed by marcelklehr** 2023-02-27 11:19 UTC
Labels: bug, 0. Needs triage

**Comment by vzsze** [comment] 2023-05-16 16:35
I still see this in 26.0.1.

**Comment by SunnyDaze** [comment] 2024-02-15 00:01
### Still seeing this bug in 28.0.2 as well.
