### ISSUE TITLE
Photos folder not showing in Photos app

### ISSUE THREAD

**Issue by TheGreatestJannet** [nextcloud/photos#320] opened 2020-04-30 10:37 UTC
The folder called Photos isn't showing the the Photos app even though it has photos in it. However other folders are showing just fine.
Is there a solution to this? it also seems to be only impacting one user on the server.

Server: 18.0.4
Client: Firefox 75

**Comment by yeupou** [comment] 2020-05-05 12:16
You should list images instead this directory, maybe that issue #208 related (arbitrary list of images handled, instead all the one of image type).

**Comment by skjnldsv** [comment] 2020-05-05 12:21
Hello @TheGreatestJannet 
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by TheGreatestJannet** [comment] 2020-05-05 12:23
Yep they are all .png which is why the folder doesn’t show up.

**Comment by yeupou** [comment] 2020-05-05 12:43
skjnldsv, 

You just marked as off-topic a comment that is actually exactly identifying the issue at hand. 
Good job.

**Comment by skjnldsv** [comment] 2020-05-05 12:46
> Good job.

Thanks :)

**Comment by skjnldsv** [comment] 2020-05-05 12:46
Duplicate of #208

**Closed by skjnldsv** 2020-05-05 12:46 UTC
Labels: 0. Needs triage, bug, needs info
