### ISSUE TITLE
.nomedia / .noimage file not respected within "Your photos"

### ISSUE THREAD

**Issue by lbdroid** [nextcloud/photos#234] opened 2020-03-12 13:11 UTC
A partial fix was implemented in https://github.com/nextcloud/photos/pull/159 for respecting .nomedia / .noimage files in a path, but unfortunately, it only applies to the "Your albums" tree.

The "Your photos" tree is still a disaster.

**Comment by skjnldsv** [comment] 2020-03-12 15:12
Not sure if doable, let's see what we can do  :)
Thanks for opening a specified one!

**Comment by bendschs** [comment] 2020-03-28 12:52
ok, so no fix yet?

**Comment by skjnldsv** [comment] 2020-03-28 12:52
> ok, so no fix yet?

As you can see by the labels and the status of this issue no.

**Comment by Queuecumber** [comment] 2020-05-03 04:24
> Not sure if doable

Not exactly filling me with confidence. This is pretty important and should have been part of the design from the beginning especially since there was previous gallery app to learn from. "Your photos" view is a real mess right now.

**Comment by Queuecumber** [comment] 2020-05-03 20:14
The problem seems to be that you've implemented "your photos" using a webdav search for any image type. (ref: src/services/PhotoSearch.js) It seems doubtful that the webdav search properties are going to be able to filter based on the existance of a folder in the same directory. 

I think using a search here is not the way to go, you should be walking the directory tree in the same way the album view is built, otherwise you risk the albums view and the "you photos" view being out of sync (exactly the cause of this bug).

Intuitively, the "your photos" view (called timeline in the code which is a MUCH better name for it) should be for showing you the exact same content from the albums view but with no hierarchy. This is in line with other modern photo sharing products such as google photos.

**Comment by skjnldsv** [comment] 2020-05-05 13:10
> This is pretty important and should have been part of the design from the beginning especially since there was previous gallery app to learn from. "Your photos" view is a real mess right now.

Agreed :/
We didn't thought there would be taht many people using the .nomedia trick :)
But what is done is done, we can only improve from there! :)



> called timeline in the code which is a MUCH better name for it

You think it makes more sense to call it `Timeline`?
Not sure how well that translates to other languages though. I definitely prefer it in English, but I fail to think of one for French :thinking: 
But that's another issue :)
Mind to open a new one for it?
Maybe others can jump in and have opînions :bowing_woman:

**Comment by Queuecumber** [comment] 2020-05-05 13:26
I think the only way to implement it without a full re-architect is to do #141 and instruct people to move photos they dont want showing out of the root photos folder. Is anyone currently working on that? I can try to look at it when I get time.

**Comment by skjnldsv** [comment] 2020-05-05 13:35
> Is anyone currently working on that? I can try to look at it when I get time.

That would be awesome Thanks :)
Yes, the plan is to do #141 first anyway, as this is more discoverable and easy than weird `.nomedia` files, which most users don't know a single thing about.

**Comment by bendschs** [comment] 2020-06-04 18:20
how come this is still open? this was a quite small feature but with big impact on usability.

**Comment by Queuecumber** [comment] 2020-06-04 18:24
It's like I described above, they made this nice new photos plugin and repeated a bunch of mistakes of the old one. There's no way to fix it in the current architecture. The only sort-of solution would be for someone to implement #141 so you can restrict your photos to a single subtree. I haven't had time to do it because I live in the US and our country is kind of in shambles right now. Also I have other PRs I'm supposed to make this one is kind of lower priority.

**Comment by JoshuaPettus** [comment] 2020-07-20 18:29
I'll be honest,  I'd much rather have the "Your Photos" hidden until some sort of solution is implemented.  What use is a broken feature that does nothing but make you look bad?  Especially seeing as it gets top billing when you open the photos app...

**Comment by 0x4a** [comment] 2020-07-20 21:42
@JoshuaPettus I agree, "your photos" does not have much use for me in the state it is in atm.

I wrote a quick userscript (tested only in Tampermonkey on Firefox) which:

* does navigate directly to albums when you open photos view
* hides "your photos" from the menu

It is not the most elegant solution for sure, but does the job :)

You have to change the include in row 8 to point to your Nextcloud installation:
https://openuserjs.org/scripts/Jekyll/nextcloud_directAlbums

HTH

**Comment by bendschs** [comment] 2020-07-20 22:27
> @JoshuaPettus I agree, "your photos" does not have much use for me in the state it is in atm.
> 
> I wrote a quick userscript (tested only in Tampermonkey on Firefox) which:
> 
> * does navigate directly to albums when you open photos view
> * hides "your photos" from the menu
> 
> It is not the most elegant solution for sure, but does the job 😉
> 
> You have to change the include in row 8 to point to your Nextcloud installation:
> https://openuserjs.org/scripts/Jekyll/nextcloud_directAlbums
> 
> HTH

it's a nice hack, does not work for the mobile app though.

**Comment by skjnldsv** [comment] 2020-07-21 07:05
> Really though what's the point? I segregate my photos for a reason. For logical, quicker access and loading.

I personally use it all the time. It's also the default view on iOS and Android. I guess it's just a matter of preferences :woman_shrugging: :)

**Comment by jippi** [comment] 2020-10-26 13:59
Hi, 

I'm just going to soft-bump this issue - I'm a huge fan of the photos app (thanks!) and use it multiple times a day for my work. 

However -- I got a bunch of media folders with sensitive data that I explicitly want to exclude from the "timeline" (I agree, its a much better name) - and it's a huge bummer that the `.nomedia` / `.nophotos` trick does not work - today I have to look "over my shoulder" to ensure no one else is watching before scrolling the timeline view, as I'm under strict NDAs and such for some of this content. 

Would it be possible in the implementation today, to add an `exclude paths` functionality as a stepping stone to a "iterate the filesystem for photos" - it would 100% solve my problem, as all my sensitive data is in a specific path prefix :)

**Comment by skjnldsv** [comment] 2020-10-26 14:09
See https://github.com/nextcloud/photos/issues/141 @jippi :)
Thanks for the kind words. We'll do our best!

**Comment by platima** [comment] 2020-12-19 03:20
Bump. This issue drives me up the wall. Still using another product for photos until this is resolved, just using NC for everything else.

**Comment by skjnldsv** [comment] 2020-12-19 07:15
@platima don't bump issues please. It's opened and free for anyone to dive at it.
Please use the GitHub reactions for support of the issues

**Comment by platima** [comment] 2020-12-19 10:56
Don't know what you mean or how to do that (nor do I care to learn as they sound like social network style interactions), but no probs you can delete my post(s)

**Comment by JoshuaPettus** [comment] 2020-12-19 14:55
That's a ridiculous policy...and insulting. The only reason that would actually matter is if you prefer issues buried.  I mean, how else are you suppose to gauge which issues actually concern people other than going to the top of the list?

Case in point, another NC patch release, but rather than fix the important problems that actually makes your software usable, (problems already addressed in the previous software you had I might add) you've made "your photos" into a timeline... So now I have all the work sensitive photos, screenshots, scanned documents, and others I don't want to see, in a timeline format... You guys aren't focusing on the right things.  Clearly the emojis aren't working.

**Comment by skjnldsv** [comment] 2020-12-19 16:52
> That's a ridiculous policy...and insulting. The only reason that would actually matter is if you prefer issues buried. I mean, how else are you suppose to gauge which issues actually concern people other than going to the top of the list?

By sorting by the reactions?
Sorry if that was perceived as "insulting"? I'm quite surprised you have felt this way, and was of course not the original intent. Bumping just sent a notification to everyone (I get around 200 a day). And if it doesn't add anything constructive to the discussion, this is not how we work here.

> Now if this were some fun project someone did on their spare time, that's one thing. But this is Nextcloud. The rising star of the Open Source community. That strives to be commercial grade software. I hold you to a higher standard. After all this time, there isn't even a pull request.

Soooo, would you be up to contribute? Should I work 80h a day to satisfy all your desire? Behind every project is a human being. If you can't understand that you're dealing with people and their own limits, please refrain yourself from posting such comments.

Nextcloud doesn't hire superheros, we're just regular people that want to make the open cloud storage a better place. I really have an issue with users coming on issues to rant on issues they feel entitled to get fixed for their personal usage.
I'll highly suggest you reconsider your collaboration expectation, as this is definitely not how I want to contribute here. The only thing those messages make me want to do is unsubscribe.

Our github issues tracker is not a place to rant, this is a place where we try our best to make things better with constructive criticism and positive discussions.
Thanks

**Comment by HannesJo0139** [comment] 2021-01-08 17:13
Where do I actually find a documentation about .nomedia / .noimage files?

**Comment by bonswouar** [comment] 2021-08-12 10:27
> Where do I actually find a documentation about .nomedia / .noimage files?

I believe this is not an official feature and thus undocumented, right?

Although, with that in mind and seeing the (kinda sensitive ^^) discussion here, why not using another way to ignore files meanwhile?
It seems using the `.nomedia` feature with webdav can't be done, at least for now. But what about some pattern exclusion for example? (some string/regex in configuration could do the trick imo)
Or simply an allowed-directories select.

**Comment by LT-Lockdown** [comment] 2021-10-05 23:33
Is there any chance that this issue will be worked on further? The Amazon Photos app was already able to hide individual photos from the Timeline and display them in a separate "Hidden Pictures" menu shortly after its release. I switched to Nextcloud because of the insecure feeling towards silicon valley etc xD and now I am missing such an important privacy feature here. In the meantime, it has already been 1 1/2 years since this topic came up here :-/

**Comment by ustrucx** [comment] 2021-11-11 03:27
would be easier to just tell the photos app where my photos are than telling it where my photos aren't, disabling ¯\_(シ)_/¯

**Comment by jcm4atx** [comment] 2021-12-03 13:37
I also believe the Photos app needs to allow us to select the directories is scans and/or have it respect .nomedia files. I have pictures I took in one place and memes, screenshots, etc. in others. I don't want the latter getting displayed with the former.

**Comment by iluvatyr** [comment] 2021-12-17 17:27
I agree to the former comments.

**Comment by HammyHavoc** [comment] 2022-01-25 20:00
Why not RegEx for a quick bodge to restrict only looking in x directory? E.g. `/Photos/, /Darktable`?

**Comment by RobMahn** [comment] 2022-02-21 00:29
This problem best solved by selecting which directories you want to include in Photos as this makes the most sense ... not having to add exclude files every time you and another directory and wondering where those images are coming from before you do so.

Right now, my music artwork is smeared all over my photos.

**Comment by flifloo** [comment] 2022-02-21 07:02
Since there is no big update in this issues, personally I looked for other alternatives
If you're looking for a full alternative of Google Photos with WebDav sync, I personally use [PhotoPrism](https://photoprism.app/)

**Comment by iluvatyr** [comment] 2022-02-21 12:34
> Since there is no big update in this issues, personally I looked for other alternatives If you're looking for a full alternative of Google Photos with WebDav sync, I personally use [PhotoPrism](https://photoprism.app/)

Photoprism is indeed a very good app that I also use. I really do not understand why this issue isnt adressed here.

**Closed** 2022-03-17 13:10 UTC
Labels: bug, 1. to develop

**Comment by skjnldsv** [comment] 2022-03-17 13:16
Thanks to @marcelklehr for implementing this! :tada:
