### ISSUE TITLE
Sharing album via public link allows removal of photos from the album

### ISSUE THREAD

**Issue by MagicTrevor** [nextcloud/photos#1456] opened 2022-11-03 22:56 UTC
**Describe the bug**
When sharing an album via public link, anyone can remove images from the album.

**To Reproduce**
1. Create an album with a photo
2. Copy Public Link
3. Log out and go to the link you copied
4. Select a photo and click on the '...' on the right

**Expected behavior**
I would expect by default a public shared link would be readonly

**Screenshots**
![image](https://user-images.githubusercontent.com/27883110/199850570-86f4facd-f04b-43a6-9a15-ec4b73290ad2.png)

**Comment by chylek** [comment] 2022-11-04 08:40
Once I click on "Remove seelected from album" it asks me to log in and when I fail to do so, it doesn't remove anything. But I also think the option to remove anything (even though login is subsequently required) shouldn't be available in public albums.

**Comment by MagicTrevor** [comment] 2022-11-04 13:58
Odd because my instance did not prompt for login, I'll have to test that again. But I agree at the very least it shouldn't be shown at all if unauthenticated.

**Comment by OJ7** [comment] 2022-11-06 21:42
> Odd because my instance did not prompt for login, I'll have to test that again. But I agree at the very least it shouldn't be shown at all if unauthenticated.

I think it just removes it from the UI. If you refresh the page, the photo is still there. For me, there was some delay between the photo being removed and the authentication prompt showing up.

**Comment by Jerome-Herbinet** [comment] 2022-11-18 15:37
True, I think that the photo selection should not allow any deletion feature, but, instead, for example, a download option. @artonge what do you think about it ?

**Comment by artonge** [comment] 2022-11-21 10:16
I think that, as long as we do not have fine graine permissions for public sharing, allowing to delete a picture by default might indeed be unwanted. I don't recall any decisions about it when the albums features was specified.
@jancborchardt, do you want to step in ?

**Comment by jzbor** [comment] 2022-11-21 11:24
I can confirm that it only works when you are logged in (at least for me). As soon as I open the same link in a private window I am no longer able tot delete pictures.

This is somewhat unfamiliar for Nextcloud though: When I share a link for a file I can choose to either share a public link or an internal link. When opening a public link though I always get the same UI with the same "permissions"/abilities to edit, delete, etc. regardless of whether I am logged in or not.

**Comment by mmyllynen** [comment] 2023-03-20 08:51
It seems to me that this is pretty serious oversight. This is how it works for me:
- create an album, get a public share link:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/82170253/226289616-6540d63a-3f74-4b88-8d91-e26aebeff44a.png">
- open the link in an incognito window - the remove from album link is available:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/82170253/226289325-6aff191f-f626-43ec-9f39-c33960d12161.png">
- click remove, return to the logged in account and refresh the gallery - the image is gone: 
<img width="444" alt="image" src="https://user-images.githubusercontent.com/82170253/226289816-42333f42-6e0d-4379-90bc-893a31ba03a7.png">

I mean.. seriously? This makes public album sharing useless. Just to be sure, tested with different browser as well, it works as descibed, without logging in.

**Comment by vectorjohn** [comment] 2023-05-03 18:59
Same as @mmyllynen , a shared link allows removing photos to anyone with the link. This does seem like a serious oversight.

**Comment by artonge** [comment] 2023-05-03 19:12
Will be fixed with the latest release by https://github.com/nextcloud/photos/pull/1749

**Closed by artonge** 2023-05-03 19:12 UTC
Labels: bug, 0. Needs triage
