### ISSUE TITLE
clicking on edit button closes the picture

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/photos#2516] opened 2024-07-04 12:50 UTC
**Describe the bug**

**To Reproduce**
1. Go to a picture
2. Click on edit (the pen)
4. Picture closes
5. click again on the picture
6. popup says there is no plugin available to display that format.

**Expected behavior**
1. upon edit click photo should be editable
2. after closing the first time, photo should be displayable again

**Screenshots**

https://github.com/nextcloud/photos/assets/87175513/ed612b17-433e-4773-b629-4907357bb3ae

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] fedora
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] daily

**Smartphone (please complete the following information):**

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

Content-Security-Policy: Ignoring “blob:” within script-src-elem: ‘strict-dynamic’ specified photos
[INFO] activity: Activity API registered 
Object { app: "activity", uid: "admin", level: "2" }
logger-CcLDq3iB.mjs:2:13897
[DEBUG] @nextcloud/files: FileListHeaders initialized 
Object { app: "@nextcloud/files", uid: "admin", level: "2" }
index.mjs:45:16
[DEBUG] core: Unified search initialized! 
Object { app: "core", uid: "admin", level: "2" }
index.mjs:45:16
OCA.Files.Sidebar initialized Sidebar.js:19:10
OCA.Comments.View initialized comments-app.js:15:8
OCA.Sharing.ShareSearch initialized ShareSearch.js:16:10
OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:16:10
OCA.Sharing.ExternalShareActions initialized ExternalShareActions.js:16:10
[DEBUG] photos: Ignored paths 
Object { app: "photos", uid: "admin", level: "2", paths: [] }
ConsoleLogger.js:65:18
[DEBUG] photos: Known .nomedia and .noimage  paths 
Object { app: "photos", uid: "admin", level: "2", files: [] }
ConsoleLogger.js:65:18
OCA.Viewer initialized viewer-main.mjs:2187:581
[INFO] viewer: No OCP.Files app found, viewer is now in standalone mode 
Object { app: "viewer", uid: "admin", level: "2" }
viewer-main.mjs:44:184629
Initializing unified search plugin-filters from talk search.js:22:9
[INFO] viewer: 6 viewer handlers registered 
Object { app: "viewer", uid: "admin", level: "2", handlers: (6) […] }
viewer-main.mjs:44:184629
session heartbeat polling started session-heartbeat.js:83:9
[DEBUG] activity: Registered new sidebar action 
Object { app: "activity", uid: "admin", level: "2" }
logger-CcLDq3iB.mjs:2:13830
[DEBUG] activity: Registered new sidebar actions factory 
Object { app: "activity", uid: "admin", level: "2" }
logger-CcLDq3iB.mjs:2:13830
[INFO] comments: Comments plugin registered for Activity sidebar action 
Object { app: "comments", uid: "admin", level: "2" }
index.mjs:48:16
Registering notifications container as a menu NotificationsApp.vue:241
Notifications permissions not yet requested NotificationsApp.vue:501
Has notify_push enabled, slowing polling to 15 minutes NotificationsApp.vue:253
Polling interval updated to 900000 NotificationsApp.vue:447
Started background fetcher as session_keepalive is enabled NotificationsApp.vue:297
[DEBUG] photos: [TiledLayout] Computing rows 
Object { app: "photos", uid: "admin", level: "2", items: [] }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] Computing visible section 
Object { app: "photos", uid: "admin", level: "2", sections: [] }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] Computing container 
Object { app: "photos", uid: "admin", level: "2" }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] isNearBottom changed 
Object { app: "photos", uid: "admin", level: "2", value: true }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] Computing visible section 
Object { app: "photos", uid: "admin", level: "2", sections: [] }
ConsoleLogger.js:65:18
[DEBUG] photos: [TiledLayout] Computing rows 
Object { app: "photos", uid: "admin", level: "2", items: (1) […] }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] Computing visible section 
Object { app: "photos", uid: "admin", level: "2", sections: (1) […] }
ConsoleLogger.js:65:18
[DEBUG] photos: [TiledLayout] Computing rows 
Object { app: "photos", uid: "admin", level: "2", items: (1) […] }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] Computing visible section 
Object { app: "photos", uid: "admin", level: "2", sections: (1) […] }
ConsoleLogger.js:65:18
[DEBUG] core: this browser is officially supported ! 🚀 
Object { app: "core", uid: "admin", level: "2" }
index.mjs:45:16
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools assistant-textGenerationReference.js:30350:55
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html assistant-textGenerationReference.js:30358:51
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools assistant-main.js:21636:55
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html assistant-main.js:21644:51
Got notification data, restoring default polling interval. NotificationsApp.vue:403
[DEBUG] unified-search: Search providers 
Object { app: "unified-search", uid: "admin", level: "2", providers: (19) […] }
index.mjs:45:16
[DEBUG] unified-search: Contacts 
Object { app: "unified-search", uid: "admin", level: "2", contacts: (25) […] }
index.mjs:45:16
[DEBUG] photos: [FetchFilesMixin] Fetched 8 new files:  
Object { 0: 16, 1: 15, 2: 17, 3: 14, 4: 13, 5: 10, 6: 12, 7: 11, app: "photos", uid: "admin", … }
ConsoleLogger.js:65:18
[DEBUG] photos: [TiledLayout] Computing rows 
Object { app: "photos", uid: "admin", level: "2", items: (6) […] }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] Computing visible section 
Object { app: "photos", uid: "admin", level: "2", sections: (6) […] }
ConsoleLogger.js:65:18
[DEBUG] photos: [TiledLayout] Computing rows 
Object { app: "photos", uid: "admin", level: "2", items: (6) […] }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] Computing visible section 
Object { app: "photos", uid: "admin", level: "2", sections: (6) […] }
ConsoleLogger.js:65:18
[DEBUG] photos: SW registered:  
Object { app: "photos", uid: "admin", level: "2", registration: ServiceWorkerRegistration }
ConsoleLogger.js:65:18
[DEBUG] photos: [FetchFilesMixin] Fetched 0 new files:  
Object { app: "photos", uid: "admin", level: "2" }
ConsoleLogger.js:65:18
[DEBUG] photos: [TiledLayout] Computing rows 
Object { app: "photos", uid: "admin", level: "2", items: (6) […] }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] Computing visible section 
Object { app: "photos", uid: "admin", level: "2", sections: (6) […] }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] isNearBottom changed 
Object { app: "photos", uid: "admin", level: "2", value: false }
ConsoleLogger.js:65:18
[DEBUG] photos: [VirtualScrolling] Computing visible section 
Object { app: "photos", uid: "admin", level: "2", sections: (6) […] }
ConsoleLogger.js:65:18
[INFO] viewer: Opening viewer for fileInfo  
Object { app: "viewer", uid: "admin", level: "2", fileInfo: {…} }
viewer-main.mjs:44:184629
[DEBUG] viewer: A files list have been provided. No folder content will be fetched. 
Object { app: "viewer", uid: "admin", level: "2" }
viewer-main.mjs:44:184542
[DEBUG] viewer: The files list changed, new current file index is 7 
Object { app: "viewer", uid: "admin", level: "2" }
viewer-main.mjs:44:184542
[DEBUG] viewer: Fetching additional files... 
Object { app: "viewer", uid: "admin", level: "2" }
viewer-main.mjs:44:184542
OCA.Viewer initialized viewer-main.mjs:2187:581
[INFO] viewer: No OCP.Files app found, viewer is now in standalone mode 
Object { app: "viewer", uid: "admin", level: "2" }
viewer-main.mjs:44:184629
Use of Mutation Events is deprecated. Use MutationObserver instead. viewer-main.mjs:2087:7064

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    3. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by skjnldsv** [comment] 2024-07-05 06:01
Duplicate of https://github.com/nextcloud/server/issues/45484

**Closed by skjnldsv** 2024-07-05 06:01 UTC
Labels: bug, 0. Needs triage
