### ISSUE TITLE
Error fetching files (JSON Decode Error)

### ISSUE THREAD

**Issue by arch-user-france1** [nextcloud/photos#1767] opened 2023-04-27 10:09 UTC
**Describe the bug**
An error seems to occur in `FetchFilesMixin`: `SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`. No request failed, but no images are displayed.

**To Reproduce**
not sure

**Expected behavior**
Images are displayed and JSON is decoded successfully.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/72965843/234830567-f26a941d-f11a-4e3f-b556-2f6ed512c296.png)
![grafik](https://user-images.githubusercontent.com/72965843/234830730-00dab1bb-bb90-41af-8596-741955bb30c2.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 112.0.1

**Browser log**
```
[ERROR] photos: Error fetching files 
Object { level: 2, app: "photos", uid: "france1", error: SyntaxError }
​
app: "photos"
​
error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
​
level: 2
​
uid: "france1"
​
<prototype>: Object { … }
[ConsoleLogger.js:46:10](webpack:///photos/node_modules/@nextcloud/logger/dist/ConsoleLogger.js)
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    updateFiles files.js:2
    updateFiles files.js:2
    A vuex.esm.js:831
    commit vuex.esm.js:437
    commit vuex.esm.js:37
    _withCommit vuex.esm.js:601
    commit vuex.esm.js:36
    commit vuex.esm.js:394
    appendFiles files.js:142
    A vuex.esm.js:736
    dispatch vuex.esm.js:490
    dispatch vuex.esm.js:393
    r FetchFilesMixin.js:98
    l FetchFilesMixin.js:2
    x FetchFilesMixin.js:2
    b FetchFilesMixin.js:2
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    fetchFiles FetchFilesMixin.js:60
    getContent Timeline.vue:237
    VueJS 4
    needContent FilesListViewer.vue:244
    VueJS 4
    isNearBottom VirtualScrolling.vue:231
    VueJS 12
    resizeObserver VirtualScrolling.vue:260
    mounted VirtualScrolling.vue:257
    VueJS 18
    init vue-router.esm.js:2980
    init vue-router.esm.js:2978
[FetchFilesMixin.js:114:12](webpack:///photos/src/mixins/FetchFilesMixin.js)
    r FetchFilesMixin.js:114
    l FetchFilesMixin.js:2
    x FetchFilesMixin.js:2
    b FetchFilesMixin.js:2
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    (Async: promise callback)
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    (Async: promise callback)
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    (Async: promise callback)
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    fetchFiles FetchFilesMixin.js:60
    getContent Timeline.vue:237
    VueJS 4
    needContent FilesListViewer.vue:244
    VueJS 4
    isNearBottom VirtualScrolling.vue:231
    VueJS 12
    resizeObserver VirtualScrolling.vue:260
    (Async: ResizeObserverCallback)
    mounted VirtualScrolling.vue:257
    VueJS 18
    init vue-router.esm.js:2980
    init vue-router.esm.js:2978
```

**Additional context**
Images have been copied to the user data folder manually, and a rescan has been triggered. Videos seem to appear, at "Videos", however no images are ever shown.
The image folder path was changed. The request even failed when it was set to the default folder that was deleted (/Photos).
There is a service worker running, but wiping the CacheStorage did not help.

**Comment by umgfoin** [comment] 2023-04-27 15:15
duplicate of #1753

**Closed by umgfoin** 2023-04-27 15:15 UTC
Labels: bug, duplicate, 0. Needs triage

**Comment by arch-user-france1** [comment] 2023-04-27 17:49
@umgfoin I apologize, I thought that issue was about an older version of Nextcloud. 
Thank you for the notice. When is the next release planned?

**Comment by umgfoin** [comment] 2023-04-27 22:48
No worries, 
I can't answer your question with confidence, as I'm not involved in the release process.
The commit was pushed to stable26, so I assume, next release of _Photos_ will come along with nc26.0.2, which is [scheduled for 2023-05-23](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule).

**Comment by fultonm** [comment] 2023-05-06 16:51
Same error on fresh install of Nextcloud All-In-One
![image](https://user-images.githubusercontent.com/13190319/236636947-1395da8b-ba90-4d33-94ec-c9cca8644346.png)

**Comment by arch-user-france1** [comment] 2023-05-07 07:24
@fultonm,
the issue has already been fixed, and the fix will be released with the next Nextcloud update to version 26.0.2.
Thank you for your assistance. Unfortunately, there's nothing left to do right now about it.
