### ISSUE TITLE
1.0.0 shared link with NC Hub 18.0 album view not working

### ISSUE THREAD

**Issue by Aesculapius** [nextcloud/photos#149] opened 2020-01-21 21:27 UTC
Installed NC18.0. Photos app is on v1.0.0.
Often share a certain folder with family to share photos in album view, with password and expiration date. I've set all options to disabled (no editing, uploading or downloading). Would expect the album to show and users to be able to click on a photo to show it in full size.

The thumbnail view can be shown (though it would be nice to be able to select the view when sharing images), but when clicking on a thumbnail, it either gets downloaded straight away or nothing happens - it doesn't pop up in a lightbox as one would expect. This worked well in NC17.

Tried viewing with Internet Explorer 11 (thumbs don't render correctly there) and with latest chrome (79.0.3945.130).

**Comment by skjnldsv** [comment] 2020-01-22 07:03
duplicate of #128

**Closed by skjnldsv** 2020-01-22 07:03 UTC
