### ISSUE TITLE
Share an Album doesn't work - Nextcloud wants to login

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/photos#1639] opened 2023-02-17 11:46 UTC
I want to share an album, but Nextcloud wants the user to log in. What do i have to do?
Nextcloud 25.0.2 - newest Photo App.

**Comment by g-work** [comment] 2023-02-20 23:28
Duplicate of https://github.com/nextcloud/photos/issues/1452 ?

**Comment by ventoux84** [comment] 2023-02-23 07:13
I want to share an album, but Nextcloud wants the user to log in when he clicks on the shared link.
Nextcloud 25.0.3 - Photo 2.0.1

**Comment by g-work** [comment] 2023-02-23 10:34
Again: Duplicate of #1452 ?

**Comment by ventoux84** [comment] 2023-02-24 06:45
With "Firefox -safe-mode" the error message is :
"Erreur au chargement de ..."

With Chromium, it asks for  user name and password in a popup window "Se connecter".

**Comment by g-work** [comment] 2023-02-24 17:12
@ventoux84 Please check, if your issue is already described in #1452

**Comment by ventoux84** [comment] 2023-02-24 18:06
After a complete reading of the  #1452, i think that this is the same thing.
Yes it's a duplicate. It's the first i have found when looking for an eventual bug in Photos.

I put back my comment in #1452.

**Comment by simonspa** [comment] 2023-02-26 14:18
Duplicate of #1452 which is solved with NC25.0.4

**Closed by simonspa** 2023-02-26 14:18 UTC
Labels: bug, 0. Needs triage
