### ISSUE TITLE
Duplicate thumbnails are generated after viewing photo.

### ISSUE THREAD

**Issue by joutwate** [nextcloud/photos#567] opened 2020-11-27 04:31 UTC
**Describe the bug**
After viewing the last photo in a list of photos, duplicate thumbnails are generated for some photos.

**To Reproduce**
1. Go to try.nextcloud.com
2. Select the 'Photos' button on the upper toolbar
3. Note the number of thumbnails shown (screenshot attached shows 9, using demo instance from try.nextcloud.com)
3. Click to view the full version of the last photo displayed (the little bird)
4. Close the view of the full photo
5. Note the number of photo thumbnails and duplicates now shown (screenshot attached shows 16, using demo instance from try.nextcloud.com)

**Expected behavior**
After viewing a photo in the web based app, the original set of photo thumbnails should be shown.

**Screenshots**
![Step 1 Photos](https://user-images.githubusercontent.com/5501471/100410990-42593d80-3025-11eb-8f88-55f17efe3dc7.png)
![Step 2 Photos](https://user-images.githubusercontent.com/5501471/100410999-45ecc480-3025-11eb-899e-31e6c292f75b.png)
![Step 3 Photos](https://user-images.githubusercontent.com/5501471/100411006-4a18e200-3025-11eb-9a6f-ed055aa76885.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Chrome 
 - Version: 87.0.4280.66

**Browser log**
![Screenshot from 2020-11-26 20-27-58](https://user-images.githubusercontent.com/5501471/100411262-18544b00-3026-11eb-9c4f-7cc6827dd691.png)
[demo1.nextcloud.com-1606451208394.log](https://github.com/nextcloud/photos/files/5605969/demo1.nextcloud.com-1606451208394.log)

**Additional context**
All reproducible on try.nextcloud.com

**Comment by skjnldsv** [comment] 2020-11-27 06:11
Hey :)

Duplicate of https://github.com/nextcloud/photos/issues/539

**Closed by skjnldsv** 2020-11-27 06:11 UTC
Labels: 0. Needs triage, bug

**Comment by joutwate** [comment] 2020-11-28 03:07
> Hey :)
> 
> Duplicate of #404

Thanks. I'll be better about searching for duplicates moving forward.
