### ISSUE TITLE
unable to see tiff files even with previews generated and Camera RAW installed

### ISSUE THREAD

**Issue by prairietree** [nextcloud/photos#1754] opened 2023-04-20 16:43 UTC
**Describe the bug**
I am unable to see tiff files or folders with only tiff files in them in Photos app. I installed Preview Generator app and got it to generate previews for tiff file. I can see the files in Files app and see that it has generated previews. I also installed Camera RAW Previews app and reran occ preview:generate-all after installing it but I am still not seeing any tiff photos in the photos app.

**To Reproduce**
1. installed Preview Generator app
2. occ preview:generate-all
3. turn on cron job to generate all new previews
4. See that previews are generated for tiff files but do not show up in photos
5. install Camera RAW Previews app
6. rerun occ preview:generate-all
7. See that tiff files still do not show up in photos

**Expected behavior**
Should be able to see tiff files in photos app.

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser Firefox
 - Version 112

**Browser log**
```
JQMIGRATE: Migrate is installed, version 3.4.0 [jquery-migrate.min.js:2:698](webpack:///nextcloud/node_modules/jquery-migrate/dist/jquery-migrate.min.js)
Proxying an event bus of version 3.0.2 with 1.3.0 [index.es.js:2337:14](webpack:///nextcloud/node_modules/@nextcloud/axios/node_modules/@nextcloud/event-bus/dist/index.es.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
Proxying an event bus of version 3.0.2 with 1.3.0 [index.es.js:2337:14](webpack:///nextcloud/node_modules/@nextcloud/axios/node_modules/@nextcloud/event-bus/dist/index.es.js)
OCA.Files.Sidebar initialized [Sidebar.js:36:10](webpack:///nextcloud/apps/files/src/services/Sidebar.js)
OCA.Files.Sidebar initialized [sidebar.js:39:8](webpack:///nextcloud/apps/files/src/sidebar.js)
Proxying an event bus of version 3.0.2 with 1.3.0 [major.js:2:14](webpack:///node_modules/semver/functions/major.js)
Proxying an event bus of version 3.0.2 with 1.3.0 [index.es.js:2337:14](webpack:///nextcloud/node_modules/@nextcloud/axios/node_modules/@nextcloud/event-bus/dist/index.es.js)
OCA.Sharing.ShareSearch initialized [ShareSearch.js:33:10](webpack:///nextcloud/apps/files_sharing/src/services/ShareSearch.js)
OCA.Sharing.ExternalLinkActions initialized [ExternalLinkActions.js:33:10](webpack:///nextcloud/apps/files_sharing/src/services/ExternalLinkActions.js)
OCA.Sharing.ExternalShareActions initialized [ExternalShareActions.js:33:10](webpack:///nextcloud/apps/files_sharing/src/services/ExternalShareActions.js)
Proxying an event bus of version 3.0.2 with 1.3.0 [index.es.js:2337:14](webpack:///nextcloud/node_modules/@nextcloud/axios/node_modules/@nextcloud/event-bus/dist/index.es.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
OCA.Comments.View initialized [comments-app.js:32:8](webpack:///nextcloud/apps/comments/src/comments-app.js)
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
Proxying an event bus of version 3.0.2 with 1.3.0 [index.es.js:2337:14](webpack:///nextcloud/node_modules/@nextcloud/axios/node_modules/@nextcloud/event-bus/dist/index.es.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
[WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config 
Object { app: "viewer", uid: "picture", level: 2, ignoredMimes: (2) […] }
[ConsoleLogger.js:56:18](webpack:///viewer/node_modules/@nextcloud/logger/dist/ConsoleLogger.js)
OCA.Viewer initialized [Viewer.js:52:25](webpack:///viewer/src/services/Viewer.js)
oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20 2 [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
Proxying an event bus of version 3.0.2 with 1.3.0 [index.es.js:2337:14](webpack:///nextcloud/node_modules/@nextcloud/axios/node_modules/@nextcloud/event-bus/dist/index.es.js)
session heartbeat polling started [session-heartbeat.js:103:9](webpack:///nextcloud/core/src/session-heartbeat.js)
Proxying an event bus of version 3.0.2 with 1.3.0 [index.es.js:2337:14](webpack:///notifications/node_modules/@nextcloud/notify_push/node_modules/@nextcloud/auth/node_modules/@nextcloud/event-bus/dist/index.es.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
Registering notifications container as a menu [NotificationsApp.vue:220](webpack:///notifications/src/NotificationsApp.vue)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
Notifications permissions granted [NotificationsApp.vue:454](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000 [NotificationsApp.vue:414](webpack:///notifications/src/NotificationsApp.vue)
Started background fetcher as session_keepalive is enabled [NotificationsApp.vue:276](webpack:///notifications/src/NotificationsApp.vue)
Got notification data [NotificationsApp.vue:377](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000 [NotificationsApp.vue:414](webpack:///notifications/src/NotificationsApp.vue)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
[photos] Grid config 
Object { marginTop: 88, marginW: 66, count: 7, gap: 8 }
[GridConfig.js:39:10](webpack:///photos/src/mixins/GridConfig.js)
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools [index.esm.js:9234:56](webpack:///photos/node_modules/@nextcloud/upload/dist/index.esm.js)
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html [index.esm.js:9241:52](webpack:///photos/node_modules/@nextcloud/upload/dist/index.esm.js)
You need to fill either the text or the ariaLabel props in the button component. 
Object { text: null, ariaLabel: null }
 
Object { _uid: 293, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
[index.module.js:2:778608](webpack:///photos/node_modules/@nextcloud/vue/dist/index.module.js)
No new notification data received [NotificationsApp.vue:382](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000 [NotificationsApp.vue:414](webpack:///notifications/src/NotificationsApp.vue)
No new notification data received [NotificationsApp.vue:382](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000 [NotificationsApp.vue:414](webpack:///notifications/src/NotificationsApp.vue)
No new notification data received [NotificationsApp.vue:382](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000
```

**Additional context**
Server configuration detail
Operating system: Linux 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64
Webserver: Apache/2.4.56 (Debian) (apache2handler)
Database: mysql 10.5.19
PHP version: 8.1.17
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, standard, posix, Reflection, Phar, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, sysvsem, zip, Zend OPcache
Nextcloud version: 26.0.0 - 26.0.0.11
List of activated apps
 - activity: 2.18.0
 - camerarawpreviews: 0.8.1
 - circles: 26.0.0
 - cloud_federation_api: 1.9.0
 - cloud_py_api: 0.1.7
 - collectives: 2.4.0
 - comments: 1.16.0
 - contactsinteraction: 1.7.0
 - dashboard: 7.6.0
 - dav: 1.25.0
 - federatedfilesharing: 1.16.0
 - federation: 1.16.0
 - files: 1.21.1
 - files_pdfviewer: 2.7.0
 - files_rightclick: 1.5.0
 - files_sharing: 1.18.0
 - files_trashbin: 1.16.0
 - files_versions: 1.19.1
 - firstrunwizard: 2.15.0
 - logreader: 2.11.0
 - lookup_server_connector: 1.14.0
 - maps: 1.0.2
 - mediadc: 0.3.5
 - nextcloud_announcements: 1.15.0
 - notifications: 2.14.0
 - oauth2: 1.14.0
 - password_policy: 1.16.0
 - photos: 2.2.0
 - previewgenerator: 5.2.2
 - privacy: 1.10.0
 - provisioning_api: 1.16.0
 - recommendations: 1.5.0
 - related_resources: 1.1.0-alpha1
 - serverinfo: 1.16.0
 - settings: 1.8.0
 - sharebymail: 1.16.0
 - support: 1.9.0
 - survey_client: 1.14.0
 - systemtags: 1.16.0
 - text: 3.7.2
 - theming: 2.1.1
 - twofactor_backupcodes: 1.15.0
 - updatenotification: 1.16.0
 - user_status: 1.6.0
 - viewer: 1.10.0
 - weather_status: 1.6.0
 - workflowengine: 2.8.0

{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "26.0.0.11",
    "overwrite.cli.url": "http:\/\/blue.kenzua.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "loglevel": 2,
    "mail_smtpmode": "smtp",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "default_phone_region": "US",
    "overwriteprotocol": "https",
    "overwritehost": "***REMOVED SENSITIVE VALUE***",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\Krita",
        "OC\\Preview\\TIFF"
    ],
    "preview_max_x": 2048,
    "preview_max_y": 2048
}

**Comment by joshtrichards** [comment] 2023-06-19 16:53
Duplicate of #849 (I think - I'll let @prairietree judge for certain!)

Thanks for your report and additional details! If you agree that #849 tracks your needs, please close this issue and subscribe yourself to #849 to receive updates (since that's where further updates on this matter will likely be tracked). Also you can click the :+1: on #849 to indicate you're impacted by the same situation (this assists the developers with prioritizing issues).

**Comment by prairietree** [comment] 2023-06-20 16:00
I will close this issue. I moved on to another app. I think it is called memories.

**Closed** 2023-06-20 16:00 UTC
Labels: bug, 0. Needs triage
