### ISSUE TITLE
On this day

### ISSUE THREAD

**Issue by LotusAxt** [nextcloud/photos#427] opened 2020-08-24 09:47 UTC
**Describe the solution you'd like**
Show all pictures that have been taken on the same calendar day, grouped by year.

**Additional context**
I've lately migrated from OneDrive to my own Nextcloud installation and one of the features that I really liked in one drive was the "On this day" notification.
It's a daily summary of all pictures in your gallery that are taken on the same calendar day as the current day.
E.g. today it would show me all pictures taken on a 24. August, grouped by year.
I really liked it because in my opinion it's a nice and easy feature to bring back old memories. 

Thank you for your great work so far and stay safe.

**Comment by jakobroehrl** [comment] 2020-08-25 10:40
duplicate of https://github.com/nextcloud/photos/issues/179 ?

**Closed** 2020-08-25 12:34 UTC
Labels: 1. to develop, enhancement
