### ISSUE TITLE
Sort by creating date instead of the edit date

### ISSUE THREAD

**Issue by ireeus** [nextcloud/photos#609] opened 2020-12-26 12:22 UTC
The app is sorting the pictures by the edit date which makes the timeline to place pictures randomly in case if you just copied the pictures.

The ideal scenario would be te extract the Exif data (using php exif_read_data() ??), write the creation dates to the database and then sort out accordingly.

**Comment by blkqi** [comment] 2021-01-04 20:55
duplicate of #87

**Closed** 2021-01-05 09:06 UTC
Labels: 0. Needs triage, enhancement
